// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: projectchat/tasks/v1/tasks.proto

package tasksv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskJson      []byte                 `protobuf:"bytes,1,opt,name=task_json,json=taskJson,proto3" json:"task_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskResponse) GetTaskJson() []byte {
	if x != nil {
		return x.TaskJson
	}
	return nil
}

type TasksByColumnResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TasksByColumnJson []byte                 `protobuf:"bytes,1,opt,name=tasks_by_column_json,json=tasksByColumnJson,proto3" json:"tasks_by_column_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TasksByColumnResponse) Reset() {
	*x = TasksByColumnResponse{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksByColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksByColumnResponse) ProtoMessage() {}

func (x *TasksByColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksByColumnResponse.ProtoReflect.Descriptor instead.
func (*TasksByColumnResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TasksByColumnResponse) GetTasksByColumnJson() []byte {
	if x != nil {
		return x.TasksByColumnJson
	}
	return nil
}

type TaskCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentJson   []byte                 `protobuf:"bytes,1,opt,name=comment_json,json=commentJson,proto3" json:"comment_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommentResponse) Reset() {
	*x = TaskCommentResponse{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommentResponse) ProtoMessage() {}

func (x *TaskCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommentResponse.ProtoReflect.Descriptor instead.
func (*TaskCommentResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCommentResponse) GetCommentJson() []byte {
	if x != nil {
		return x.CommentJson
	}
	return nil
}

type TaskCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentsJson  []byte                 `protobuf:"bytes,1,opt,name=comments_json,json=commentsJson,proto3" json:"comments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommentsResponse) Reset() {
	*x = TaskCommentsResponse{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommentsResponse) ProtoMessage() {}

func (x *TaskCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommentsResponse.ProtoReflect.Descriptor instead.
func (*TaskCommentsResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *TaskCommentsResponse) GetCommentsJson() []byte {
	if x != nil {
		return x.CommentsJson
	}
	return nil
}

type CreateTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectColumnId  string                 `protobuf:"bytes,2,opt,name=project_column_id,json=projectColumnId,proto3" json:"project_column_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Code             string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	RequestUserId    string                 `protobuf:"bytes,6,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	Priority         string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate          *string                `protobuf:"bytes,8,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"` // RFC3339
	ResponsibleId    *string                `protobuf:"bytes,9,opt,name=responsible_id,json=responsibleId,proto3,oneof" json:"responsible_id,omitempty"`
	Tags             []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	DependsOnTaskIds []string               `protobuf:"bytes,11,rep,name=depends_on_task_ids,json=dependsOnTaskIds,proto3" json:"depends_on_task_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetProjectColumnId() string {
	if x != nil {
		return x.ProjectColumnId
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateTaskRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *CreateTaskRequest) GetResponsibleId() string {
	if x != nil && x.ResponsibleId != nil {
		return *x.ResponsibleId
	}
	return ""
}

func (x *CreateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTaskRequest) GetDependsOnTaskIds() []string {
	if x != nil {
		return x.DependsOnTaskIds
	}
	return nil
}

type GetTaskByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIdRequest) Reset() {
	*x = GetTaskByIdRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdRequest) ProtoMessage() {}

func (x *GetTaskByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTaskByIdRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskByIdRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GroupTasksByColumnRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectColumnIds []string               `protobuf:"bytes,3,rep,name=project_column_ids,json=projectColumnIds,proto3" json:"project_column_ids,omitempty"`
	Archived         bool                   `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	TaskOrder        string                 `protobuf:"bytes,5,opt,name=task_order,json=taskOrder,proto3" json:"task_order,omitempty"`
	CursorUpdatedAt  *string                `protobuf:"bytes,6,opt,name=cursor_updated_at,json=cursorUpdatedAt,proto3,oneof" json:"cursor_updated_at,omitempty"` // RFC3339
	Limit            int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupTasksByColumnRequest) Reset() {
	*x = GroupTasksByColumnRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTasksByColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTasksByColumnRequest) ProtoMessage() {}

func (x *GroupTasksByColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTasksByColumnRequest.ProtoReflect.Descriptor instead.
func (*GroupTasksByColumnRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *GroupTasksByColumnRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GroupTasksByColumnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupTasksByColumnRequest) GetProjectColumnIds() []string {
	if x != nil {
		return x.ProjectColumnIds
	}
	return nil
}

func (x *GroupTasksByColumnRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *GroupTasksByColumnRequest) GetTaskOrder() string {
	if x != nil {
		return x.TaskOrder
	}
	return ""
}

func (x *GroupTasksByColumnRequest) GetCursorUpdatedAt() string {
	if x != nil && x.CursorUpdatedAt != nil {
		return *x.CursorUpdatedAt
	}
	return ""
}

func (x *GroupTasksByColumnRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindTaskByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTaskByCodeRequest) Reset() {
	*x = FindTaskByCodeRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTaskByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTaskByCodeRequest) ProtoMessage() {}

func (x *FindTaskByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTaskByCodeRequest.ProtoReflect.Descriptor instead.
func (*FindTaskByCodeRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *FindTaskByCodeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FindTaskByCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindTaskByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MoveTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestUserId   string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	AfterTaskId     *string                `protobuf:"bytes,3,opt,name=after_task_id,json=afterTaskId,proto3,oneof" json:"after_task_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectColumnId string                 `protobuf:"bytes,5,opt,name=project_column_id,json=projectColumnId,proto3" json:"project_column_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MoveTaskRequest) Reset() {
	*x = MoveTaskRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTaskRequest) ProtoMessage() {}

func (x *MoveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTaskRequest.ProtoReflect.Descriptor instead.
func (*MoveTaskRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *MoveTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MoveTaskRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *MoveTaskRequest) GetAfterTaskId() string {
	if x != nil && x.AfterTaskId != nil {
		return *x.AfterTaskId
	}
	return ""
}

func (x *MoveTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MoveTaskRequest) GetProjectColumnId() string {
	if x != nil {
		return x.ProjectColumnId
	}
	return ""
}

type UpdateTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Code             *string                `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`
	ProjectColumnId  string                 `protobuf:"bytes,5,opt,name=project_column_id,json=projectColumnId,proto3" json:"project_column_id,omitempty"`
	RequestUserId    string                 `protobuf:"bytes,6,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	Priority         string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate          *string                `protobuf:"bytes,8,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"` // RFC3339
	ResponsibleId    *string                `protobuf:"bytes,9,opt,name=responsible_id,json=responsibleId,proto3,oneof" json:"responsible_id,omitempty"`
	Tags             []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	DependsOnTaskIds []string               `protobuf:"bytes,11,rep,name=depends_on_task_ids,json=dependsOnTaskIds,proto3" json:"depends_on_task_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UpdateTaskRequest) GetProjectColumnId() string {
	if x != nil {
		return x.ProjectColumnId
	}
	return ""
}

func (x *UpdateTaskRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *UpdateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *UpdateTaskRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *UpdateTaskRequest) GetResponsibleId() string {
	if x != nil && x.ResponsibleId != nil {
		return *x.ResponsibleId
	}
	return ""
}

func (x *UpdateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTaskRequest) GetDependsOnTaskIds() []string {
	if x != nil {
		return x.DependsOnTaskIds
	}
	return nil
}

type MarkTaskDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestUserId string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskDoneRequest) Reset() {
	*x = MarkTaskDoneRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskDoneRequest) ProtoMessage() {}

func (x *MarkTaskDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskDoneRequest.ProtoReflect.Descriptor instead.
func (*MarkTaskDoneRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *MarkTaskDoneRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MarkTaskDoneRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type AssignTaskToSelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestUserId string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskToSelfRequest) Reset() {
	*x = AssignTaskToSelfRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskToSelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskToSelfRequest) ProtoMessage() {}

func (x *AssignTaskToSelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskToSelfRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskToSelfRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *AssignTaskToSelfRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignTaskToSelfRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

type CreateTaskCommentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestUserId   string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentCommentId *string                `protobuf:"bytes,4,opt,name=parent_comment_id,json=parentCommentId,proto3,oneof" json:"parent_comment_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTaskCommentRequest) Reset() {
	*x = CreateTaskCommentRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskCommentRequest) ProtoMessage() {}

func (x *CreateTaskCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskCommentRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTaskCommentRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskCommentRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *CreateTaskCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTaskCommentRequest) GetParentCommentId() string {
	if x != nil && x.ParentCommentId != nil {
		return *x.ParentCommentId
	}
	return ""
}

type ListTaskCommentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RequestUserId   string                 `protobuf:"bytes,2,opt,name=request_user_id,json=requestUserId,proto3" json:"request_user_id,omitempty"`
	Limit           int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Before          *string                `protobuf:"bytes,4,opt,name=before,proto3,oneof" json:"before,omitempty"` // RFC3339
	BeforeCommentId *string                `protobuf:"bytes,5,opt,name=before_comment_id,json=beforeCommentId,proto3,oneof" json:"before_comment_id,omitempty"`
	After           *string                `protobuf:"bytes,6,opt,name=after,proto3,oneof" json:"after,omitempty"` // RFC3339
	AfterCommentId  *string                `protobuf:"bytes,7,opt,name=after_comment_id,json=afterCommentId,proto3,oneof" json:"after_comment_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTaskCommentsRequest) Reset() {
	*x = ListTaskCommentsRequest{}
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskCommentsRequest) ProtoMessage() {}

func (x *ListTaskCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_tasks_v1_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListTaskCommentsRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_tasks_v1_tasks_proto_rawDescGZIP(), []int{13}
}

func (x *ListTaskCommentsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListTaskCommentsRequest) GetRequestUserId() string {
	if x != nil {
		return x.RequestUserId
	}
	return ""
}

func (x *ListTaskCommentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTaskCommentsRequest) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

func (x *ListTaskCommentsRequest) GetBeforeCommentId() string {
	if x != nil && x.BeforeCommentId != nil {
		return *x.BeforeCommentId
	}
	return ""
}

func (x *ListTaskCommentsRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *ListTaskCommentsRequest) GetAfterCommentId() string {
	if x != nil && x.AfterCommentId != nil {
		return *x.AfterCommentId
	}
	return ""
}

var File_projectchat_tasks_v1_tasks_proto protoreflect.FileDescriptor

const file_projectchat_tasks_v1_tasks_proto_rawDesc = "" +
	"\n" +
	" projectchat/tasks/v1/tasks.proto\x12\x14projectchat.tasks.v1\"+\n" +
	"\fTaskResponse\x12\x1b\n" +
	"\ttask_json\x18\x01 \x01(\fR\btaskJson\"H\n" +
	"\x15TasksByColumnResponse\x12/\n" +
	"\x14tasks_by_column_json\x18\x01 \x01(\fR\x11tasksByColumnJson\"8\n" +
	"\x13TaskCommentResponse\x12!\n" +
	"\fcomment_json\x18\x01 \x01(\fR\vcommentJson\";\n" +
	"\x14TaskCommentsResponse\x12#\n" +
	"\rcomments_json\x18\x01 \x01(\fR\fcommentsJson\"\x9d\x03\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12*\n" +
	"\x11project_column_id\x18\x02 \x01(\tR\x0fprojectColumnId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12&\n" +
	"\x0frequest_user_id\x18\x06 \x01(\tR\rrequestUserId\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x1e\n" +
	"\bdue_date\x18\b \x01(\tH\x00R\adueDate\x88\x01\x01\x12*\n" +
	"\x0eresponsible_id\x18\t \x01(\tH\x01R\rresponsibleId\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12-\n" +
	"\x13depends_on_task_ids\x18\v \x03(\tR\x10dependsOnTaskIdsB\v\n" +
	"\t_due_dateB\x11\n" +
	"\x0f_responsible_id\"F\n" +
	"\x12GetTaskByIdRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x99\x02\n" +
	"\x19GroupTasksByColumnRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x12project_column_ids\x18\x03 \x03(\tR\x10projectColumnIds\x12\x1a\n" +
	"\barchived\x18\x04 \x01(\bR\barchived\x12\x1d\n" +
	"\n" +
	"task_order\x18\x05 \x01(\tR\ttaskOrder\x12/\n" +
	"\x11cursor_updated_at\x18\x06 \x01(\tH\x00R\x0fcursorUpdatedAt\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limitB\x14\n" +
	"\x12_cursor_updated_at\"c\n" +
	"\x15FindTaskByCodeRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xd8\x01\n" +
	"\x0fMoveTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\x12'\n" +
	"\rafter_task_id\x18\x03 \x01(\tH\x00R\vafterTaskId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12*\n" +
	"\x11project_column_id\x18\x05 \x01(\tR\x0fprojectColumnIdB\x10\n" +
	"\x0e_after_task_id\"\xa5\x03\n" +
	"\x11UpdateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\x04code\x18\x04 \x01(\tH\x00R\x04code\x88\x01\x01\x12*\n" +
	"\x11project_column_id\x18\x05 \x01(\tR\x0fprojectColumnId\x12&\n" +
	"\x0frequest_user_id\x18\x06 \x01(\tR\rrequestUserId\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x1e\n" +
	"\bdue_date\x18\b \x01(\tH\x01R\adueDate\x88\x01\x01\x12*\n" +
	"\x0eresponsible_id\x18\t \x01(\tH\x02R\rresponsibleId\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12-\n" +
	"\x13depends_on_task_ids\x18\v \x03(\tR\x10dependsOnTaskIdsB\a\n" +
	"\x05_codeB\v\n" +
	"\t_due_dateB\x11\n" +
	"\x0f_responsible_id\"V\n" +
	"\x13MarkTaskDoneRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\"Z\n" +
	"\x17AssignTaskToSelfRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\"\xbc\x01\n" +
	"\x18CreateTaskCommentRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12/\n" +
	"\x11parent_comment_id\x18\x04 \x01(\tH\x00R\x0fparentCommentId\x88\x01\x01B\x14\n" +
	"\x12_parent_comment_id\"\xc8\x02\n" +
	"\x17ListTaskCommentsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12&\n" +
	"\x0frequest_user_id\x18\x02 \x01(\tR\rrequestUserId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06before\x18\x04 \x01(\tH\x00R\x06before\x88\x01\x01\x12/\n" +
	"\x11before_comment_id\x18\x05 \x01(\tH\x01R\x0fbeforeCommentId\x88\x01\x01\x12\x19\n" +
	"\x05after\x18\x06 \x01(\tH\x02R\x05after\x88\x01\x01\x12-\n" +
	"\x10after_comment_id\x18\a \x01(\tH\x03R\x0eafterCommentId\x88\x01\x01B\t\n" +
	"\a_beforeB\x14\n" +
	"\x12_before_comment_idB\b\n" +
	"\x06_afterB\x13\n" +
	"\x11_after_comment_id2\xf3\a\n" +
	"\vTaskService\x12Y\n" +
	"\n" +
	"CreateTask\x12'.projectchat.tasks.v1.CreateTaskRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12[\n" +
	"\vGetTaskById\x12(.projectchat.tasks.v1.GetTaskByIdRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12r\n" +
	"\x12GroupTasksByColumn\x12/.projectchat.tasks.v1.GroupTasksByColumnRequest\x1a+.projectchat.tasks.v1.TasksByColumnResponse\x12a\n" +
	"\x0eFindTaskByCode\x12+.projectchat.tasks.v1.FindTaskByCodeRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12U\n" +
	"\bMoveTask\x12%.projectchat.tasks.v1.MoveTaskRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12Y\n" +
	"\n" +
	"UpdateTask\x12'.projectchat.tasks.v1.UpdateTaskRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12]\n" +
	"\fMarkTaskDone\x12).projectchat.tasks.v1.MarkTaskDoneRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12e\n" +
	"\x10AssignTaskToSelf\x12-.projectchat.tasks.v1.AssignTaskToSelfRequest\x1a\".projectchat.tasks.v1.TaskResponse\x12n\n" +
	"\x11CreateTaskComment\x12..projectchat.tasks.v1.CreateTaskCommentRequest\x1a).projectchat.tasks.v1.TaskCommentResponse\x12m\n" +
	"\x10ListTaskComments\x12-.projectchat.tasks.v1.ListTaskCommentsRequest\x1a*.projectchat.tasks.v1.TaskCommentsResponseBBZ@github.com/gabrielnakaema/project-chat/internal/tasks/v1;tasksv1b\x06proto3"

var (
	file_projectchat_tasks_v1_tasks_proto_rawDescOnce sync.Once
	file_projectchat_tasks_v1_tasks_proto_rawDescData []byte
)

func file_projectchat_tasks_v1_tasks_proto_rawDescGZIP() []byte {
	file_projectchat_tasks_v1_tasks_proto_rawDescOnce.Do(func() {
		file_projectchat_tasks_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectchat_tasks_v1_tasks_proto_rawDesc), len(file_projectchat_tasks_v1_tasks_proto_rawDesc)))
	})
	return file_projectchat_tasks_v1_tasks_proto_rawDescData
}

var file_projectchat_tasks_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_projectchat_tasks_v1_tasks_proto_goTypes = []any{
	(*TaskResponse)(nil),              // 0: projectchat.tasks.v1.TaskResponse
	(*TasksByColumnResponse)(nil),     // 1: projectchat.tasks.v1.TasksByColumnResponse
	(*TaskCommentResponse)(nil),       // 2: projectchat.tasks.v1.TaskCommentResponse
	(*TaskCommentsResponse)(nil),      // 3: projectchat.tasks.v1.TaskCommentsResponse
	(*CreateTaskRequest)(nil),         // 4: projectchat.tasks.v1.CreateTaskRequest
	(*GetTaskByIdRequest)(nil),        // 5: projectchat.tasks.v1.GetTaskByIdRequest
	(*GroupTasksByColumnRequest)(nil), // 6: projectchat.tasks.v1.GroupTasksByColumnRequest
	(*FindTaskByCodeRequest)(nil),     // 7: projectchat.tasks.v1.FindTaskByCodeRequest
	(*MoveTaskRequest)(nil),           // 8: projectchat.tasks.v1.MoveTaskRequest
	(*UpdateTaskRequest)(nil),         // 9: projectchat.tasks.v1.UpdateTaskRequest
	(*MarkTaskDoneRequest)(nil),       // 10: projectchat.tasks.v1.MarkTaskDoneRequest
	(*AssignTaskToSelfRequest)(nil),   // 11: projectchat.tasks.v1.AssignTaskToSelfRequest
	(*CreateTaskCommentRequest)(nil),  // 12: projectchat.tasks.v1.CreateTaskCommentRequest
	(*ListTaskCommentsRequest)(nil),   // 13: projectchat.tasks.v1.ListTaskCommentsRequest
}
var file_projectchat_tasks_v1_tasks_proto_depIdxs = []int32{
	4,  // 0: projectchat.tasks.v1.TaskService.CreateTask:input_type -> projectchat.tasks.v1.CreateTaskRequest
	5,  // 1: projectchat.tasks.v1.TaskService.GetTaskById:input_type -> projectchat.tasks.v1.GetTaskByIdRequest
	6,  // 2: projectchat.tasks.v1.TaskService.GroupTasksByColumn:input_type -> projectchat.tasks.v1.GroupTasksByColumnRequest
	7,  // 3: projectchat.tasks.v1.TaskService.FindTaskByCode:input_type -> projectchat.tasks.v1.FindTaskByCodeRequest
	8,  // 4: projectchat.tasks.v1.TaskService.MoveTask:input_type -> projectchat.tasks.v1.MoveTaskRequest
	9,  // 5: projectchat.tasks.v1.TaskService.UpdateTask:input_type -> projectchat.tasks.v1.UpdateTaskRequest
	10, // 6: projectchat.tasks.v1.TaskService.MarkTaskDone:input_type -> projectchat.tasks.v1.MarkTaskDoneRequest
	11, // 7: projectchat.tasks.v1.TaskService.AssignTaskToSelf:input_type -> projectchat.tasks.v1.AssignTaskToSelfRequest
	12, // 8: projectchat.tasks.v1.TaskService.CreateTaskComment:input_type -> projectchat.tasks.v1.CreateTaskCommentRequest
	13, // 9: projectchat.tasks.v1.TaskService.ListTaskComments:input_type -> projectchat.tasks.v1.ListTaskCommentsRequest
	0,  // 10: projectchat.tasks.v1.TaskService.CreateTask:output_type -> projectchat.tasks.v1.TaskResponse
	0,  // 11: projectchat.tasks.v1.TaskService.GetTaskById:output_type -> projectchat.tasks.v1.TaskResponse
	1,  // 12: projectchat.tasks.v1.TaskService.GroupTasksByColumn:output_type -> projectchat.tasks.v1.TasksByColumnResponse
	0,  // 13: projectchat.tasks.v1.TaskService.FindTaskByCode:output_type -> projectchat.tasks.v1.TaskResponse
	0,  // 14: projectchat.tasks.v1.TaskService.MoveTask:output_type -> projectchat.tasks.v1.TaskResponse
	0,  // 15: projectchat.tasks.v1.TaskService.UpdateTask:output_type -> projectchat.tasks.v1.TaskResponse
	0,  // 16: projectchat.tasks.v1.TaskService.MarkTaskDone:output_type -> projectchat.tasks.v1.TaskResponse
	0,  // 17: projectchat.tasks.v1.TaskService.AssignTaskToSelf:output_type -> projectchat.tasks.v1.TaskResponse
	2,  // 18: projectchat.tasks.v1.TaskService.CreateTaskComment:output_type -> projectchat.tasks.v1.TaskCommentResponse
	3,  // 19: projectchat.tasks.v1.TaskService.ListTaskComments:output_type -> projectchat.tasks.v1.TaskCommentsResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_projectchat_tasks_v1_tasks_proto_init() }
func file_projectchat_tasks_v1_tasks_proto_init() {
	if File_projectchat_tasks_v1_tasks_proto != nil {
		return
	}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[4].OneofWrappers = []any{}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[6].OneofWrappers = []any{}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[8].OneofWrappers = []any{}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[9].OneofWrappers = []any{}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[12].OneofWrappers = []any{}
	file_projectchat_tasks_v1_tasks_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectchat_tasks_v1_tasks_proto_rawDesc), len(file_projectchat_tasks_v1_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectchat_tasks_v1_tasks_proto_goTypes,
		DependencyIndexes: file_projectchat_tasks_v1_tasks_proto_depIdxs,
		MessageInfos:      file_projectchat_tasks_v1_tasks_proto_msgTypes,
	}.Build()
	File_projectchat_tasks_v1_tasks_proto = out.File
	file_projectchat_tasks_v1_tasks_proto_goTypes = nil
	file_projectchat_tasks_v1_tasks_proto_depIdxs = nil
}
