// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: projectchat/tasks/v1/tasks.proto

package tasksv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_CreateTask_FullMethodName         = "/projectchat.tasks.v1.TaskService/CreateTask"
	TaskService_GetTaskById_FullMethodName        = "/projectchat.tasks.v1.TaskService/GetTaskById"
	TaskService_GroupTasksByColumn_FullMethodName = "/projectchat.tasks.v1.TaskService/GroupTasksByColumn"
	TaskService_SearchTasks_FullMethodName        = "/projectchat.tasks.v1.TaskService/SearchTasks"
	TaskService_FindTaskByCode_FullMethodName     = "/projectchat.tasks.v1.TaskService/FindTaskByCode"
	TaskService_MoveTask_FullMethodName           = "/projectchat.tasks.v1.TaskService/MoveTask"
	TaskService_UpdateTask_FullMethodName         = "/projectchat.tasks.v1.TaskService/UpdateTask"
	TaskService_MarkTaskDone_FullMethodName       = "/projectchat.tasks.v1.TaskService/MarkTaskDone"
	TaskService_AssignTaskToSelf_FullMethodName   = "/projectchat.tasks.v1.TaskService/AssignTaskToSelf"
	TaskService_CreateTaskComment_FullMethodName  = "/projectchat.tasks.v1.TaskService/CreateTaskComment"
	TaskService_ListTaskComments_FullMethodName   = "/projectchat.tasks.v1.TaskService/ListTaskComments"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskService exposes task and task-comment operations over gRPC so the api
// service (which hosts the MCP agent endpoint) can invoke them without
// instantiating the tasks slice in-process.
//
// Responses carry the shared domain object marshaled as JSON so the gRPC
// contract mirrors the HTTP/WebSocket contract exactly, rather than duplicating
// the rich Task/TaskComment shape in protobuf.
type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTaskById(ctx context.Context, in *GetTaskByIdRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GroupTasksByColumn(ctx context.Context, in *GroupTasksByColumnRequest, opts ...grpc.CallOption) (*TasksByColumnResponse, error)
	SearchTasks(ctx context.Context, in *SearchTasksRequest, opts ...grpc.CallOption) (*SearchTasksResponse, error)
	FindTaskByCode(ctx context.Context, in *FindTaskByCodeRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	MarkTaskDone(ctx context.Context, in *MarkTaskDoneRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	AssignTaskToSelf(ctx context.Context, in *AssignTaskToSelfRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	CreateTaskComment(ctx context.Context, in *CreateTaskCommentRequest, opts ...grpc.CallOption) (*TaskCommentResponse, error)
	ListTaskComments(ctx context.Context, in *ListTaskCommentsRequest, opts ...grpc.CallOption) (*TaskCommentsResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskById(ctx context.Context, in *GetTaskByIdRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GroupTasksByColumn(ctx context.Context, in *GroupTasksByColumnRequest, opts ...grpc.CallOption) (*TasksByColumnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksByColumnResponse)
	err := c.cc.Invoke(ctx, TaskService_GroupTasksByColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SearchTasks(ctx context.Context, in *SearchTasksRequest, opts ...grpc.CallOption) (*SearchTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_SearchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FindTaskByCode(ctx context.Context, in *FindTaskByCodeRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_FindTaskByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_MoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MarkTaskDone(ctx context.Context, in *MarkTaskDoneRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_MarkTaskDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AssignTaskToSelf(ctx context.Context, in *AssignTaskToSelfRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_AssignTaskToSelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateTaskComment(ctx context.Context, in *CreateTaskCommentRequest, opts ...grpc.CallOption) (*TaskCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCommentResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateTaskComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTaskComments(ctx context.Context, in *ListTaskCommentsRequest, opts ...grpc.CallOption) (*TaskCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskCommentsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTaskComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
//
// TaskService exposes task and task-comment operations over gRPC so the api
// service (which hosts the MCP agent endpoint) can invoke them without
// instantiating the tasks slice in-process.
//
// Responses carry the shared domain object marshaled as JSON so the gRPC
// contract mirrors the HTTP/WebSocket contract exactly, rather than duplicating
// the rich Task/TaskComment shape in protobuf.
type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*TaskResponse, error)
	GetTaskById(context.Context, *GetTaskByIdRequest) (*TaskResponse, error)
	GroupTasksByColumn(context.Context, *GroupTasksByColumnRequest) (*TasksByColumnResponse, error)
	SearchTasks(context.Context, *SearchTasksRequest) (*SearchTasksResponse, error)
	FindTaskByCode(context.Context, *FindTaskByCodeRequest) (*TaskResponse, error)
	MoveTask(context.Context, *MoveTaskRequest) (*TaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*TaskResponse, error)
	MarkTaskDone(context.Context, *MarkTaskDoneRequest) (*TaskResponse, error)
	AssignTaskToSelf(context.Context, *AssignTaskToSelfRequest) (*TaskResponse, error)
	CreateTaskComment(context.Context, *CreateTaskCommentRequest) (*TaskCommentResponse, error)
	ListTaskComments(context.Context, *ListTaskCommentsRequest) (*TaskCommentsResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskById(context.Context, *GetTaskByIdRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskById not implemented")
}
func (UnimplementedTaskServiceServer) GroupTasksByColumn(context.Context, *GroupTasksByColumnRequest) (*TasksByColumnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupTasksByColumn not implemented")
}
func (UnimplementedTaskServiceServer) SearchTasks(context.Context, *SearchTasksRequest) (*SearchTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTasks not implemented")
}
func (UnimplementedTaskServiceServer) FindTaskByCode(context.Context, *FindTaskByCodeRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindTaskByCode not implemented")
}
func (UnimplementedTaskServiceServer) MoveTask(context.Context, *MoveTaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskServiceServer) MarkTaskDone(context.Context, *MarkTaskDoneRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTaskDone not implemented")
}
func (UnimplementedTaskServiceServer) AssignTaskToSelf(context.Context, *AssignTaskToSelfRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTaskToSelf not implemented")
}
func (UnimplementedTaskServiceServer) CreateTaskComment(context.Context, *CreateTaskCommentRequest) (*TaskCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTaskComment not implemented")
}
func (UnimplementedTaskServiceServer) ListTaskComments(context.Context, *ListTaskCommentsRequest) (*TaskCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaskComments not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskById(ctx, req.(*GetTaskByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GroupTasksByColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupTasksByColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GroupTasksByColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GroupTasksByColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GroupTasksByColumn(ctx, req.(*GroupTasksByColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SearchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SearchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SearchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SearchTasks(ctx, req.(*SearchTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FindTaskByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTaskByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FindTaskByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FindTaskByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FindTaskByCode(ctx, req.(*FindTaskByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MoveTask(ctx, req.(*MoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MarkTaskDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTaskDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MarkTaskDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MarkTaskDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MarkTaskDone(ctx, req.(*MarkTaskDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AssignTaskToSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskToSelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AssignTaskToSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AssignTaskToSelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AssignTaskToSelf(ctx, req.(*AssignTaskToSelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateTaskComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTaskComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTaskComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTaskComment(ctx, req.(*CreateTaskCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTaskComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTaskComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTaskComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTaskComments(ctx, req.(*ListTaskCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projectchat.tasks.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTaskById",
			Handler:    _TaskService_GetTaskById_Handler,
		},
		{
			MethodName: "GroupTasksByColumn",
			Handler:    _TaskService_GroupTasksByColumn_Handler,
		},
		{
			MethodName: "SearchTasks",
			Handler:    _TaskService_SearchTasks_Handler,
		},
		{
			MethodName: "FindTaskByCode",
			Handler:    _TaskService_FindTaskByCode_Handler,
		},
		{
			MethodName: "MoveTask",
			Handler:    _TaskService_MoveTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "MarkTaskDone",
			Handler:    _TaskService_MarkTaskDone_Handler,
		},
		{
			MethodName: "AssignTaskToSelf",
			Handler:    _TaskService_AssignTaskToSelf_Handler,
		},
		{
			MethodName: "CreateTaskComment",
			Handler:    _TaskService_CreateTaskComment_Handler,
		},
		{
			MethodName: "ListTaskComments",
			Handler:    _TaskService_ListTaskComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projectchat/tasks/v1/tasks.proto",
}
