http:
  routers:
    websocket-service:
      rule: "PathPrefix(`/ws`)"
      service: websocket-service
      priority: 20
    notification-service:
      rule: "PathPrefix(`/notifications`)"
      service: notification-service
      priority: 10
    api:
      rule: "PathPrefix(`/`)"
      service: api
      priority: 1

  services:
    websocket-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3336"
    notification-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3335"
    api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4333"
