// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: chats.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (project_id) VALUES ($1) returning id
`

func (q *Queries) CreateChat(ctx context.Context, projectID pgtype.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChat, projectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChatMember = `-- name: CreateChatMember :exec
INSERT INTO chat_members (user_id, chat_id, last_seen_at, joined_at) VALUES ($1, $2, $3, $4)
`

type CreateChatMemberParams struct {
	UserID     uuid.UUID
	ChatID     uuid.UUID
	LastSeenAt pgtype.Timestamptz
	JoinedAt   pgtype.Timestamptz
}

func (q *Queries) CreateChatMember(ctx context.Context, arg CreateChatMemberParams) error {
	_, err := q.db.Exec(ctx, createChatMember,
		arg.UserID,
		arg.ChatID,
		arg.LastSeenAt,
		arg.JoinedAt,
	)
	return err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (chat_id, user_id, content, created_at, updated_at, message_type) VALUES ($1, $2, $3, $4, $5, $6) returning id
`

type CreateChatMessageParams struct {
	ChatID      uuid.UUID
	UserID      pgtype.UUID
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	MessageType string
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ChatID,
		arg.UserID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MessageType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createGeneralChat = `-- name: CreateGeneralChat :one
INSERT INTO chats (chat_type) VALUES ('general') RETURNING id
`

func (q *Queries) CreateGeneralChat(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createGeneralChat)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChatMember = `-- name: DeleteChatMember :exec
DELETE FROM chat_members WHERE user_id = $1 AND chat_id = $2
`

type DeleteChatMemberParams struct {
	UserID uuid.UUID
	ChatID uuid.UUID
}

func (q *Queries) DeleteChatMember(ctx context.Context, arg DeleteChatMemberParams) error {
	_, err := q.db.Exec(ctx, deleteChatMember, arg.UserID, arg.ChatID)
	return err
}

const findGeneralChatByExactMembers = `-- name: FindGeneralChatByExactMembers :one
SELECT c.id FROM chats c
WHERE c.chat_type = 'general'
  AND (SELECT COUNT(*) FROM chat_members WHERE chat_id = c.id) = cardinality($1::uuid[])
  AND NOT EXISTS (
    SELECT 1 FROM chat_members cm
    WHERE cm.chat_id = c.id AND cm.user_id != ALL($1::uuid[])
  )
LIMIT 1
`

func (q *Queries) FindGeneralChatByExactMembers(ctx context.Context, dollar_1 []uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findGeneralChatByExactMembers, dollar_1)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChatById = `-- name: GetChatById :one
with chat_members_cte as (
	select 
		cm.chat_id as member_chat_id,
		cm.user_id as member_user_id,
		cm.joined_at as member_joined_at,
		cm.last_seen_at as member_last_seen_at,
		u."name" as member_name
	from chat_members cm
	left join users u on u.id = cm.user_id
)
select 
	c.id, c.project_id, c.created_at, c.updated_at, c.chat_type,
	coalesce(
		jsonb_agg(
			jsonb_build_object(
				'chat_id', cm.member_chat_id,
				'user_id', cm.member_user_id,
				'last_seen_at', cm.member_last_seen_at,
				'joined_at', cm.member_joined_at,
				'user',
				jsonb_build_object(
					'id', cm.member_user_id,
					'name', cm.member_name
				)
			)
		) filter (where cm.member_user_id is not null and cm.member_chat_id is not null)
	, '[]'::jsonb) as members
from chats c
left join chat_members_cte cm on cm.member_chat_id = c.id
where c.id = $1
group by c.id
`

type GetChatByIdRow struct {
	ID        uuid.UUID
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ChatType  string
	Members   interface{}
}

func (q *Queries) GetChatById(ctx context.Context, id uuid.UUID) (GetChatByIdRow, error) {
	row := q.db.QueryRow(ctx, getChatById, id)
	var i GetChatByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChatType,
		&i.Members,
	)
	return i, err
}

const getChatByProjectId = `-- name: GetChatByProjectId :one
with chat_members_cte as (
	select 
		cm.chat_id as member_chat_id,
		cm.user_id as member_user_id,
		cm.joined_at as member_joined_at,
		cm.last_seen_at as member_last_seen_at,
		u."name" as member_name
	from chat_members cm
	left join users u on u.id = cm.user_id
)
select 
	c.id, c.project_id, c.created_at, c.updated_at, c.chat_type,
	coalesce(
		jsonb_agg(
			jsonb_build_object(
				'chat_id', cm.member_chat_id,
				'user_id', cm.member_user_id,
				'last_seen_at', cm.member_last_seen_at,
				'joined_at', cm.member_joined_at,
				'user',
				jsonb_build_object(
					'id', cm.member_user_id,
					'name', cm.member_name
				)
			)
		) filter (where cm.member_user_id is not null and cm.member_chat_id is not null)
	, '[]'::jsonb) as members
from chats c
left join chat_members_cte cm on cm.member_chat_id = c.id
where c.project_id = $1
group by c.id
`

type GetChatByProjectIdRow struct {
	ID        uuid.UUID
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ChatType  string
	Members   interface{}
}

func (q *Queries) GetChatByProjectId(ctx context.Context, projectID pgtype.UUID) (GetChatByProjectIdRow, error) {
	row := q.db.QueryRow(ctx, getChatByProjectId, projectID)
	var i GetChatByProjectIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChatType,
		&i.Members,
	)
	return i, err
}

const getChatMessageById = `-- name: GetChatMessageById :one
SELECT id, chat_id, content, created_at, updated_at, user_id, message_type
FROM chat_messages
WHERE id = $1
`

func (q *Queries) GetChatMessageById(ctx context.Context, id uuid.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageById, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.MessageType,
	)
	return i, err
}

const getUnreadCountByChatId = `-- name: GetUnreadCountByChatId :one
WITH unread_messages AS (
	SELECT 1
	FROM chat_messages cm
	JOIN chat_members cmm ON cmm.chat_id = cm.chat_id AND cmm.user_id = $2
	WHERE cm.chat_id = $1
		AND cm.user_id IS DISTINCT FROM $2
		AND (cm.created_at, cm.id) > (cmm.last_seen_at, '00000000-0000-0000-0000-000000000000'::uuid)
	ORDER BY cm.created_at DESC, cm.id DESC
	LIMIT $3
)
SELECT
	LEAST(COUNT(*), $3 - 1)::int AS unread_count,
	COUNT(*) = $3 AS has_more_unread
FROM unread_messages
`

type GetUnreadCountByChatIdParams struct {
	ChatID  uuid.UUID
	UserID  uuid.UUID
	Column3 interface{}
}

type GetUnreadCountByChatIdRow struct {
	UnreadCount   int32
	HasMoreUnread bool
}

func (q *Queries) GetUnreadCountByChatId(ctx context.Context, arg GetUnreadCountByChatIdParams) (GetUnreadCountByChatIdRow, error) {
	row := q.db.QueryRow(ctx, getUnreadCountByChatId, arg.ChatID, arg.UserID, arg.Column3)
	var i GetUnreadCountByChatIdRow
	err := row.Scan(&i.UnreadCount, &i.HasMoreUnread)
	return i, err
}

const listChatMessageReads = `-- name: ListChatMessageReads :many
SELECT
	cmr.chat_message_id,
	cmr.user_id,
	cmr.read_at,
	u.name,
	u.email
FROM chat_message_reads cmr
JOIN users u ON u.id = cmr.user_id
JOIN chat_messages cm ON cm.id = cmr.chat_message_id
WHERE cmr.chat_message_id = $1
	AND cm.user_id IS DISTINCT FROM cmr.user_id
ORDER BY cmr.read_at ASC, u.name ASC
`

type ListChatMessageReadsRow struct {
	ChatMessageID uuid.UUID
	UserID        uuid.UUID
	ReadAt        pgtype.Timestamptz
	Name          string
	Email         string
}

func (q *Queries) ListChatMessageReads(ctx context.Context, chatMessageID uuid.UUID) ([]ListChatMessageReadsRow, error) {
	rows, err := q.db.Query(ctx, listChatMessageReads, chatMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessageReadsRow
	for rows.Next() {
		var i ListChatMessageReadsRow
		if err := rows.Scan(
			&i.ChatMessageID,
			&i.UserID,
			&i.ReadAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
select
	cm.id,
	cm.chat_id,
	cm.content,
	cm.created_at,
	cm.updated_at,
	cm.user_id,
	cm.message_type,
	u.name as user_name,
	coalesce(count(cmr.user_id), 0)::int as reads_count
from chat_messages cm
left join users u on u.id = cm.user_id
left join chat_message_reads cmr on cmr.chat_message_id = cm.id
where cm.chat_id = $1
and (cm.created_at, cm.id) < ($2, $3::uuid)
group by cm.id, u.name
order by cm.created_at desc, cm.id desc
limit $4
`

type ListChatMessagesParams struct {
	ChatID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	Column3   uuid.UUID
	Limit     int32
}

type ListChatMessagesRow struct {
	ID          uuid.UUID
	ChatID      uuid.UUID
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      pgtype.UUID
	MessageType string
	UserName    pgtype.Text
	ReadsCount  int32
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages,
		arg.ChatID,
		arg.CreatedAt,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.MessageType,
			&i.UserName,
			&i.ReadsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneralChatsByUserId = `-- name: ListGeneralChatsByUserId :many
WITH chat_members_cte AS (
	SELECT
		cm.chat_id AS member_chat_id,
		u.id AS member_user_id,
		cm.joined_at AS member_joined_at,
		cm.last_seen_at AS member_last_seen_at,
		u.name AS member_name,
		u.email AS member_email
	FROM chat_members cm
	JOIN users u ON u.id = cm.user_id
)
SELECT
	c.id,
	c.project_id,
	c.chat_type,
	c.created_at,
	c.updated_at,
	coalesce(unread_stats.unread_count, 0)::int as unread_count,
	coalesce(unread_stats.has_more_unread, false) as has_more_unread,
	coalesce(
		jsonb_agg(
			jsonb_build_object(
				'chat_id', cm.member_chat_id,
				'user_id', cm.member_user_id,
				'last_seen_at', cm.member_last_seen_at,
				'joined_at', cm.member_joined_at,
				'user',
				jsonb_build_object(
					'id', cm.member_user_id,
					'name', cm.member_name,
					'email', cm.member_email
				)
			)
		) FILTER (WHERE cm.member_user_id IS NOT NULL)
	, '[]'::jsonb) AS members
FROM chats c
JOIN chat_members cm_self ON cm_self.chat_id = c.id AND cm_self.user_id = $1
LEFT JOIN chat_members_cte cm ON cm.member_chat_id = c.id
LEFT JOIN LATERAL (
	SELECT
		LEAST(COUNT(*), $2 - 1)::int AS unread_count,
		COUNT(*) = $2 AS has_more_unread
	FROM (
		SELECT 1
		FROM chat_messages chat_message
		WHERE chat_message.chat_id = c.id
			AND chat_message.user_id IS DISTINCT FROM $1
			AND (chat_message.created_at, chat_message.id) > (
				cm_self.last_seen_at,
				'00000000-0000-0000-0000-000000000000'::uuid
			)
		ORDER BY chat_message.created_at DESC, chat_message.id DESC
		LIMIT $2
	) AS unread_messages
) unread_stats ON true
WHERE c.chat_type = 'general'
GROUP BY c.id, unread_stats.unread_count, unread_stats.has_more_unread
ORDER BY c.updated_at DESC
`

type ListGeneralChatsByUserIdParams struct {
	UserID  uuid.UUID
	Column2 interface{}
}

type ListGeneralChatsByUserIdRow struct {
	ID            uuid.UUID
	ProjectID     pgtype.UUID
	ChatType      string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	UnreadCount   int32
	HasMoreUnread bool
	Members       interface{}
}

func (q *Queries) ListGeneralChatsByUserId(ctx context.Context, arg ListGeneralChatsByUserIdParams) ([]ListGeneralChatsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, listGeneralChatsByUserId, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeneralChatsByUserIdRow
	for rows.Next() {
		var i ListGeneralChatsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChatType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnreadCount,
			&i.HasMoreUnread,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatMemberLastSeenAt = `-- name: UpdateChatMemberLastSeenAt :exec
UPDATE chat_members
SET last_seen_at = GREATEST(last_seen_at, $1)
WHERE user_id = $2 AND chat_id = $3
`

type UpdateChatMemberLastSeenAtParams struct {
	LastSeenAt pgtype.Timestamptz
	UserID     uuid.UUID
	ChatID     uuid.UUID
}

func (q *Queries) UpdateChatMemberLastSeenAt(ctx context.Context, arg UpdateChatMemberLastSeenAtParams) error {
	_, err := q.db.Exec(ctx, updateChatMemberLastSeenAt, arg.LastSeenAt, arg.UserID, arg.ChatID)
	return err
}

const updateChatUpdatedAt = `-- name: UpdateChatUpdatedAt :exec
UPDATE chats SET updated_at = $1 WHERE id = $2
`

type UpdateChatUpdatedAtParams struct {
	UpdatedAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) UpdateChatUpdatedAt(ctx context.Context, arg UpdateChatUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, updateChatUpdatedAt, arg.UpdatedAt, arg.ID)
	return err
}

const upsertChatMessageReadsUpTo = `-- name: UpsertChatMessageReadsUpTo :exec
INSERT INTO chat_message_reads (chat_message_id, user_id, read_at)
SELECT cm.id, $2, $3
FROM chat_messages cm
WHERE cm.chat_id = $1
	AND (cm.created_at, cm.id) <= ($4, $5::uuid)
	AND cm.user_id IS DISTINCT FROM $2
ON CONFLICT (chat_message_id, user_id)
DO UPDATE SET read_at = GREATEST(chat_message_reads.read_at, EXCLUDED.read_at)
`

type UpsertChatMessageReadsUpToParams struct {
	ChatID    uuid.UUID
	UserID    uuid.UUID
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Column5   uuid.UUID
}

func (q *Queries) UpsertChatMessageReadsUpTo(ctx context.Context, arg UpsertChatMessageReadsUpToParams) error {
	_, err := q.db.Exec(ctx, upsertChatMessageReadsUpTo,
		arg.ChatID,
		arg.UserID,
		arg.ReadAt,
		arg.CreatedAt,
		arg.Column5,
	)
	return err
}
