// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mcp_api_keys.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPAPIKey = `-- name: CreateMCPAPIKey :one
INSERT INTO mcp_api_keys (user_id, name, key_prefix, secret_hash, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateMCPAPIKeyParams struct {
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	SecretHash string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateMCPAPIKey(ctx context.Context, arg CreateMCPAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createMCPAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.SecretHash,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMCPAPIKeyScope = `-- name: CreateMCPAPIKeyScope :exec
INSERT INTO mcp_api_key_scopes (api_key_id, scope, created_at)
VALUES ($1, $2, $3)
`

type CreateMCPAPIKeyScopeParams struct {
	ApiKeyID  uuid.UUID
	Scope     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMCPAPIKeyScope(ctx context.Context, arg CreateMCPAPIKeyScopeParams) error {
	_, err := q.db.Exec(ctx, createMCPAPIKeyScope, arg.ApiKeyID, arg.Scope, arg.CreatedAt)
	return err
}

const deleteMCPAPIKeyScopes = `-- name: DeleteMCPAPIKeyScopes :exec
DELETE FROM mcp_api_key_scopes
WHERE api_key_id = $1
`

func (q *Queries) DeleteMCPAPIKeyScopes(ctx context.Context, apiKeyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMCPAPIKeyScopes, apiKeyID)
	return err
}

const getMCPAPIKeyByIDForUser = `-- name: GetMCPAPIKeyByIDForUser :one
SELECT
  k.id,
  k.user_id,
  k.name,
  k.key_prefix,
  k.secret_hash,
  k.created_at,
  k.last_used_at,
  k.revoked_at,
  COALESCE(array_agg(s.scope ORDER BY s.scope) FILTER (WHERE s.scope IS NOT NULL), '{}'::text[]) AS scopes
FROM mcp_api_keys k
LEFT JOIN mcp_api_key_scopes s ON s.api_key_id = k.id
WHERE k.id = $1 AND k.user_id = $2
GROUP BY k.id
`

type GetMCPAPIKeyByIDForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetMCPAPIKeyByIDForUserRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	SecretHash string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	Scopes     interface{}
}

func (q *Queries) GetMCPAPIKeyByIDForUser(ctx context.Context, arg GetMCPAPIKeyByIDForUserParams) (GetMCPAPIKeyByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getMCPAPIKeyByIDForUser, arg.ID, arg.UserID)
	var i GetMCPAPIKeyByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const getMCPAPIKeyByPrefix = `-- name: GetMCPAPIKeyByPrefix :one
SELECT
  k.id,
  k.user_id,
  k.name,
  k.key_prefix,
  k.secret_hash,
  k.created_at,
  k.last_used_at,
  k.revoked_at,
  COALESCE(array_agg(s.scope ORDER BY s.scope) FILTER (WHERE s.scope IS NOT NULL), '{}'::text[]) AS scopes
FROM mcp_api_keys k
LEFT JOIN mcp_api_key_scopes s ON s.api_key_id = k.id
WHERE k.key_prefix = $1
GROUP BY k.id
`

type GetMCPAPIKeyByPrefixRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	SecretHash string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	Scopes     interface{}
}

func (q *Queries) GetMCPAPIKeyByPrefix(ctx context.Context, keyPrefix string) (GetMCPAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getMCPAPIKeyByPrefix, keyPrefix)
	var i GetMCPAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scopes,
	)
	return i, err
}

const listMCPAPIKeysByUserID = `-- name: ListMCPAPIKeysByUserID :many
SELECT
  k.id,
  k.user_id,
  k.name,
  k.key_prefix,
  k.secret_hash,
  k.created_at,
  k.last_used_at,
  k.revoked_at,
  COALESCE(array_agg(s.scope ORDER BY s.scope) FILTER (WHERE s.scope IS NOT NULL), '{}'::text[]) AS scopes
FROM mcp_api_keys k
LEFT JOIN mcp_api_key_scopes s ON s.api_key_id = k.id
WHERE k.user_id = $1
GROUP BY k.id
ORDER BY k.created_at DESC, k.id DESC
`

type ListMCPAPIKeysByUserIDRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	SecretHash string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	Scopes     interface{}
}

func (q *Queries) ListMCPAPIKeysByUserID(ctx context.Context, userID uuid.UUID) ([]ListMCPAPIKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listMCPAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPAPIKeysByUserIDRow
	for rows.Next() {
		var i ListMCPAPIKeysByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMCPAPIKey = `-- name: RevokeMCPAPIKey :execrows
UPDATE mcp_api_keys
SET revoked_at = COALESCE(revoked_at, $3::timestamptz)
WHERE id = $1 AND user_id = $2
`

type RevokeMCPAPIKeyParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeMCPAPIKey(ctx context.Context, arg RevokeMCPAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCPAPIKey, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMCPAPIKeyLastUsedAt = `-- name: TouchMCPAPIKeyLastUsedAt :exec
UPDATE mcp_api_keys
SET last_used_at = $2::timestamptz
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < $3::timestamptz)
`

type TouchMCPAPIKeyLastUsedAtParams struct {
	ID         uuid.UUID
	LastUsedAt pgtype.Timestamptz
	CutoffAt   pgtype.Timestamptz
}

func (q *Queries) TouchMCPAPIKeyLastUsedAt(ctx context.Context, arg TouchMCPAPIKeyLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, touchMCPAPIKeyLastUsedAt, arg.ID, arg.LastUsedAt, arg.CutoffAt)
	return err
}

const updateMCPAPIKeyName = `-- name: UpdateMCPAPIKeyName :execrows
UPDATE mcp_api_keys
SET name = $3
WHERE id = $1 AND user_id = $2
`

type UpdateMCPAPIKeyNameParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
}

func (q *Queries) UpdateMCPAPIKeyName(ctx context.Context, arg UpdateMCPAPIKeyNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMCPAPIKeyName, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
