// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChatMember struct {
	UserID     uuid.UUID
	ChatID     uuid.UUID
	LastSeenAt pgtype.Timestamptz
	JoinedAt   pgtype.Timestamptz
}

type ChatMessage struct {
	ID          uuid.UUID
	ChatID      uuid.UUID
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      pgtype.UUID
	MessageType string
}

type Project struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectMember struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
}

type RefreshToken struct {
	ID        uuid.UUID
	Active    bool
	Token     string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Task struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Title       string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	AuthorID    uuid.UUID
}

type TaskChange struct {
	ID          uuid.UUID
	TaskID      uuid.UUID
	UserID      pgtype.UUID
	Description string
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
