// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ChatType  string
}

type ChatMember struct {
	UserID     uuid.UUID
	ChatID     uuid.UUID
	LastSeenAt pgtype.Timestamptz
	JoinedAt   pgtype.Timestamptz
}

type ChatMessage struct {
	ID          uuid.UUID
	ChatID      uuid.UUID
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      pgtype.UUID
	MessageType string
}

type Project struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectActivityLog struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	ActorID      uuid.UUID
	ActivityType string
	ActivityData []byte
	EntityType   pgtype.Text
	EntityID     pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ProjectMember struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
}

type RefreshToken struct {
	ID        uuid.UUID
	Active    bool
	Token     string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Task struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Title         string
	Description   string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AuthorID      uuid.UUID
	Priority      string
	DueDate       pgtype.Timestamptz
	DoneAt        pgtype.Timestamptz
	ResponsibleID pgtype.UUID
	TaskOrder     string
}

type TaskChange struct {
	ID              uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdateID        pgtype.UUID
	Field           string
	OldValue        string
	NewValue        string
	SubjectID       pgtype.UUID
	OldValueID      pgtype.UUID
	NewValueID      pgtype.UUID
	OldDisplayValue pgtype.Text
	NewDisplayValue pgtype.Text
}

type TaskComment struct {
	ID              uuid.UUID
	TaskID          uuid.UUID
	UserID          uuid.UUID
	Content         string
	ParentCommentID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TaskTag struct {
	TaskID    uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type TaskUpdate struct {
	ID         uuid.UUID
	TaskID     uuid.UUID
	UserID     uuid.UUID
	UpdateType string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
