// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: project_activity_logs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectActivityLog = `-- name: CreateProjectActivityLog :one
INSERT INTO project_activity_logs (
    project_id,
    actor_id,
    activity_type,
    activity_data,
    entity_type,
    entity_id
  )
VALUES ($1, $2, $3, $4, $5, $6)
returning id
`

type CreateProjectActivityLogParams struct {
	ProjectID    uuid.UUID
	ActorID      uuid.UUID
	ActivityType string
	ActivityData []byte
	EntityType   pgtype.Text
	EntityID     pgtype.UUID
}

func (q *Queries) CreateProjectActivityLog(ctx context.Context, arg CreateProjectActivityLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProjectActivityLog,
		arg.ProjectID,
		arg.ActorID,
		arg.ActivityType,
		arg.ActivityData,
		arg.EntityType,
		arg.EntityID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjectActivityLogs = `-- name: ListProjectActivityLogs :many
WITH user_projects AS (
  SELECT DISTINCT pm.project_id
  FROM project_members pm
  WHERE (pm.user_id = $5::uuid OR $5::uuid IS NULL)
),
activity_logs AS (
  SELECT 
    pal.id,
    pal.project_id,
    pal.actor_id,
    pal.activity_type,
    pal.action_origin,
    COALESCE(pal.activity_data, '{}'::jsonb) as activity_data,
    pal.entity_type,
    pal.entity_id,
    pal.created_at,
    pal.updated_at
  FROM project_activity_logs pal
  WHERE 
    $6::boolean = false 
    OR pal.project_id IN (SELECT project_id FROM user_projects)
),
task_entities AS (
  SELECT 
    t.id,
    jsonb_build_object(
      'id', t.id,
      'project_id', t.project_id,
      'title', t.title,
      'description', t.description,
      'status', CASE
        WHEN t.archived_at IS NOT NULL THEN 'archived'
        ELSE lower(COALESCE(pc.name, ''))
      END,
      'project_column_id', t.project_column_id,
      'project_column', CASE
        WHEN pc.id IS NULL THEN NULL
        ELSE jsonb_build_object(
          'id', pc.id,
          'project_id', pc.project_id,
          'name', pc.name,
          'color', pc.color,
          'position', pc.position,
          'is_done_column', pc.is_done_column,
          'created_at', pc.created_at,
          'updated_at', pc.updated_at
        )
      END,
      'archived_at', t.archived_at,
      'created_at', t.created_at,
      'updated_at', t.updated_at
    ) as entity_data
  FROM tasks t
  LEFT JOIN project_columns pc ON pc.id = t.project_column_id
),
project_member_entities AS (
  SELECT 
    pm.id,
    jsonb_build_object(
      'id', pm.id,
      'user_id', pm.user_id,
      'project_id', pm.project_id,
      'role', pm.role,
      'user', jsonb_build_object(
        'id', u.id,
        'name', u.name,
        'email', u.email,
        'created_at', u.created_at,
        'updated_at', u.updated_at
      )
    ) as entity_data
  FROM project_members pm
  JOIN users u ON pm.user_id = u.id
)
SELECT
  al.id,
  al.project_id,
  al.actor_id,
  al.activity_type,
  al.action_origin,
  al.activity_data,
  al.entity_type,
  al.entity_id,
  al.created_at,
  al.updated_at,
  p.name as project_name,
  p.description as project_description,
  p.user_id as project_user_id,
  p.created_at as project_created_at,
  p.updated_at as project_updated_at,
  actor.name as actor_name,
  actor.email as actor_email,
  CASE 
    WHEN al.entity_type = 'task' THEN te.entity_data
    WHEN al.entity_type = 'project.member' THEN pme.entity_data
    WHEN al.entity_type = 'project' THEN '{}'::jsonb
    ELSE '{}'::jsonb
  END as entity
FROM activity_logs al
JOIN projects p ON al.project_id = p.id
JOIN users actor ON al.actor_id = actor.id
LEFT JOIN task_entities te ON al.entity_type = 'task' AND al.entity_id = te.id
LEFT JOIN project_member_entities pme ON al.entity_type = 'project.member' AND al.entity_id = pme.id
WHERE (al.project_id = $1::uuid OR $1::uuid IS NULL)
AND (
  $2::timestamptz IS NULL 
  OR (al.created_at, al.id) < ($2::timestamptz, $3::uuid)
)
ORDER BY al.created_at DESC, al.id DESC
LIMIT (COALESCE($4::integer, 0) + 1)
`

type ListProjectActivityLogsParams struct {
	ProjectID       pgtype.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeID        pgtype.UUID
	Limit           pgtype.Int4
	UserID          pgtype.UUID
	FilterByUser    bool
}

type ListProjectActivityLogsRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	ActorID            uuid.UUID
	ActivityType       string
	ActionOrigin       string
	ActivityData       []byte
	EntityType         pgtype.Text
	EntityID           pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ProjectName        string
	ProjectDescription string
	ProjectUserID      uuid.UUID
	ProjectCreatedAt   pgtype.Timestamptz
	ProjectUpdatedAt   pgtype.Timestamptz
	ActorName          string
	ActorEmail         string
	Entity             []byte
}

func (q *Queries) ListProjectActivityLogs(ctx context.Context, arg ListProjectActivityLogsParams) ([]ListProjectActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listProjectActivityLogs,
		arg.ProjectID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.Limit,
		arg.UserID,
		arg.FilterByUser,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectActivityLogsRow
	for rows.Next() {
		var i ListProjectActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ActorID,
			&i.ActivityType,
			&i.ActionOrigin,
			&i.ActivityData,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.ProjectUserID,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
			&i.ActorName,
			&i.ActorEmail,
			&i.Entity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
