// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: projects.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO
  projects (user_id, name, description)
VALUES
  ($1, $2, $3) returning id
`

type CreateProjectParams struct {
	UserID      uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.Description)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProjectColumn = `-- name: CreateProjectColumn :one
INSERT INTO
  project_columns (project_id, name, description, color, position, is_done_column)
VALUES
  ($1, $2, $3, $4, $5, $6) returning id
`

type CreateProjectColumnParams struct {
	ProjectID    uuid.UUID
	Name         string
	Description  string
	Color        string
	Position     int32
	IsDoneColumn bool
}

func (q *Queries) CreateProjectColumn(ctx context.Context, arg CreateProjectColumnParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProjectColumn,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
		arg.IsDoneColumn,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO
  project_members (user_id, project_id, role)
VALUES
  ($1, $2, $3) returning id
`

type CreateProjectMemberParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	Role      string
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProjectMember, arg.UserID, arg.ProjectID, arg.Role)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProjectColumn = `-- name: DeleteProjectColumn :exec
DELETE FROM project_columns
WHERE id = $1
  AND project_id = $2
`

type DeleteProjectColumnParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) DeleteProjectColumn(ctx context.Context, arg DeleteProjectColumnParams) error {
	_, err := q.db.Exec(ctx, deleteProjectColumn, arg.ID, arg.ProjectID)
	return err
}

const getProjectById = `-- name: GetProjectById :one
WITH project_members_cte AS (
  SELECT
    pm.id as project_member_id,
    pm.user_id as project_member_user_id,
    pm.project_id,
    pm.role,
    u.id as user_id,
    u.name,
    u.email,
    u.created_at,
    u.updated_at
  FROM
    project_members pm
    JOIN users u ON u.id = pm.user_id
  WHERE
    pm.project_id = $1
), project_columns_cte AS (
  SELECT
    ps.id,
    ps.project_id,
    ps.name,
    ps.description,
    ps.color,
    ps.position,
    ps.is_done_column,
    ps.created_at,
    ps.updated_at
  FROM project_columns ps
  WHERE ps.project_id = $1
)
SELECT
  p.id, p.user_id, p.name, p.description, p.created_at, p.updated_at,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id',
        pm.project_member_id,
        'user_id',
        pm.project_member_user_id,
        'project_id',
        pm.project_id,
        'role',
        pm.role,
        'user',
        jsonb_build_object(
          'id',
          pm.user_id,
          'name',
          pm.name,
          'email',
          pm.email,
          'created_at',
          pm.created_at,
          'updated_at',
          pm.updated_at
        )
      )
    ) filter (
      where
        pm.project_member_id is not null
    ),
    '[]' :: jsonb
  ) as members,
  (
    SELECT coalesce(jsonb_agg(
      jsonb_build_object(
        'id', ps.id,
        'project_id', ps.project_id,
        'name', ps.name,
        'description', ps.description,
        'color', ps.color,
        'position', ps.position,
        'is_done_column', ps.is_done_column,
        'created_at', ps.created_at,
        'updated_at', ps.updated_at
      )
      ORDER BY ps.position ASC, ps.created_at ASC
    ), '[]'::jsonb)
    FROM project_columns_cte ps
  ) as columns
FROM
  projects p
  LEFT JOIN project_members_cte pm ON pm.project_id = p.id
WHERE
  p.id = $1
GROUP BY
  p.id
`

type GetProjectByIdRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Members     interface{}
	Columns     interface{}
}

func (q *Queries) GetProjectById(ctx context.Context, id uuid.UUID) (GetProjectByIdRow, error) {
	row := q.db.QueryRow(ctx, getProjectById, id)
	var i GetProjectByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Members,
		&i.Columns,
	)
	return i, err
}

const getProjectColumnById = `-- name: GetProjectColumnById :one
SELECT id, project_id, name, description, color, position, is_done_column, created_at, updated_at
FROM project_columns
WHERE id = $1
`

type GetProjectColumnByIdRow struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Name         string
	Description  string
	Color        string
	Position     int32
	IsDoneColumn bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetProjectColumnById(ctx context.Context, id uuid.UUID) (GetProjectColumnByIdRow, error) {
	row := q.db.QueryRow(ctx, getProjectColumnById, id)
	var i GetProjectColumnByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.IsDoneColumn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMemberByUserIdAndProjectId = `-- name: GetProjectMemberByUserIdAndProjectId :one
SELECT id, user_id, project_id, role FROM project_members
WHERE user_id = $1
  AND project_id = $2
`

type GetProjectMemberByUserIdAndProjectIdParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectMemberByUserIdAndProjectId(ctx context.Context, arg GetProjectMemberByUserIdAndProjectIdParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMemberByUserIdAndProjectId, arg.UserID, arg.ProjectID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Role,
	)
	return i, err
}

const listProjectMembersByProjectId = `-- name: ListProjectMembersByProjectId :many
SELECT
  pm.id,
  pm.user_id as project_member_user_id,
  pm.project_id as project_member_project_id,
  pm.role as project_member_role,
  u.id as user_id,
  u.name as user_name,
  u.email as user_email,
  u.created_at as user_created_at,
  u.updated_at as user_updated_at
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY u.name ASC
`

type ListProjectMembersByProjectIdRow struct {
	ID                     uuid.UUID
	ProjectMemberUserID    uuid.UUID
	ProjectMemberProjectID uuid.UUID
	ProjectMemberRole      string
	UserID                 uuid.UUID
	UserName               string
	UserEmail              string
	UserCreatedAt          pgtype.Timestamptz
	UserUpdatedAt          pgtype.Timestamptz
}

func (q *Queries) ListProjectMembersByProjectId(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembersByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersByProjectIdRow
	for rows.Next() {
		var i ListProjectMembersByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectMemberUserID,
			&i.ProjectMemberProjectID,
			&i.ProjectMemberRole,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserId = `-- name: ListProjectsByUserId :many
WITH project_members_cte AS (
  SELECT
    pm.id as project_member_id,
    pm.user_id as project_member_user_id,
    pm.project_id,
    pm.role,
    u.id as user_id,
    u.name,
    u.email,
    u.created_at,
    u.updated_at
  FROM
    project_members pm
    JOIN users u ON u.id = pm.user_id
), project_columns_cte AS (
  SELECT
    ps.id,
    ps.project_id,
    ps.name,
    ps.description,
    ps.color,
    ps.position,
    ps.is_done_column,
    ps.created_at,
    ps.updated_at
  FROM project_columns ps
)
SELECT
  p.id, p.user_id, p.name, p.description, p.created_at, p.updated_at,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id',
        pm.project_member_id,
        'user_id',
        pm.project_member_user_id,
        'project_id',
        pm.project_id,
        'role',
        pm.role,
        'user',
        jsonb_build_object(
          'id',
          pm.user_id,
          'name',
          pm.name,
          'email',
          pm.email,
          'created_at',
          pm.created_at,
          'updated_at',
          pm.updated_at
        )
      )
    ) filter (
      where
        pm.project_member_id is not null
    ),
    '[]' :: jsonb
  ) as members,
  (
    SELECT coalesce(jsonb_agg(
      jsonb_build_object(
        'id', ps.id,
        'project_id', ps.project_id,
        'name', ps.name,
        'description', ps.description,
        'color', ps.color,
        'position', ps.position,
        'is_done_column', ps.is_done_column,
        'created_at', ps.created_at,
        'updated_at', ps.updated_at
      )
      ORDER BY ps.position ASC, ps.created_at ASC
    ), '[]'::jsonb)
    FROM project_columns_cte ps
    WHERE ps.project_id = p.id
  ) as columns
FROM
  projects p
  INNER JOIN project_members_cte pm ON pm.project_id = p.id
WHERE
  p.id IN (
    SELECT DISTINCT project_id
    FROM project_members
    WHERE project_members.user_id = $1
    AND (
      $2::text is null
      or role = $2::text
    )
  )
  AND ($3::text IS NULL OR (p.name ILIKE '%' || $3::text || '%' OR p.description ILIKE '%' || $3::text || '%'))
GROUP BY
  p.id
ORDER BY p.updated_at DESC
`

type ListProjectsByUserIdParams struct {
	UserID uuid.UUID
	Role   pgtype.Text
	Query  pgtype.Text
}

type ListProjectsByUserIdRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Members     interface{}
	Columns     interface{}
}

func (q *Queries) ListProjectsByUserId(ctx context.Context, arg ListProjectsByUserIdParams) ([]ListProjectsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserId, arg.UserID, arg.Role, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByUserIdRow
	for rows.Next() {
		var i ListProjectsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Members,
			&i.Columns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectUpdatedAt = `-- name: MarkProjectUpdatedAt :exec
UPDATE projects
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkProjectUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markProjectUpdatedAt, id)
	return err
}

const reassignTasksToProjectColumn = `-- name: ReassignTasksToProjectColumn :exec
UPDATE tasks
SET
  project_column_id = $1,
  done_at = CASE
    WHEN $2::boolean = true AND archived_at IS NULL AND done_at IS NULL THEN CURRENT_TIMESTAMP
    WHEN $2::boolean = false THEN NULL
    ELSE done_at
  END,
  updated_at = CURRENT_TIMESTAMP
WHERE project_column_id = $3
`

type ReassignTasksToProjectColumnParams struct {
	ProjectColumnID   uuid.UUID
	Column2           bool
	ProjectColumnID_2 uuid.UUID
}

func (q *Queries) ReassignTasksToProjectColumn(ctx context.Context, arg ReassignTasksToProjectColumnParams) error {
	_, err := q.db.Exec(ctx, reassignTasksToProjectColumn, arg.ProjectColumnID, arg.Column2, arg.ProjectColumnID_2)
	return err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE user_id = $1
  AND project_id = $2
`

type RemoveProjectMemberParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.UserID, arg.ProjectID)
	return err
}

const removeProjectTasksResponsibleByUserId = `-- name: RemoveProjectTasksResponsibleByUserId :exec
UPDATE tasks
  SET responsible_id = NULL
  WHERE responsible_id = $1
  AND project_id = $2
`

type RemoveProjectTasksResponsibleByUserIdParams struct {
	ResponsibleID pgtype.UUID
	ProjectID     uuid.UUID
}

func (q *Queries) RemoveProjectTasksResponsibleByUserId(ctx context.Context, arg RemoveProjectTasksResponsibleByUserIdParams) error {
	_, err := q.db.Exec(ctx, removeProjectTasksResponsibleByUserId, arg.ResponsibleID, arg.ProjectID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE
  projects
SET
  name = $1,
  description = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $3
`

type UpdateProjectParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	return err
}

const updateProjectColumn = `-- name: UpdateProjectColumn :exec
UPDATE
  project_columns
SET
  name = $1,
  description = $2,
  color = $3,
  position = $4,
  is_done_column = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $6
  AND project_id = $7
`

type UpdateProjectColumnParams struct {
	Name         string
	Description  string
	Color        string
	Position     int32
	IsDoneColumn bool
	ID           uuid.UUID
	ProjectID    uuid.UUID
}

func (q *Queries) UpdateProjectColumn(ctx context.Context, arg UpdateProjectColumnParams) error {
	_, err := q.db.Exec(ctx, updateProjectColumn,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
		arg.IsDoneColumn,
		arg.ID,
		arg.ProjectID,
	)
	return err
}
