// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: task_comments.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskComment = `-- name: CreateTaskComment :one
INSERT INTO task_comments (task_id, user_id, content, parent_comment_id) VALUES ($1, $2, $3, $4) returning id
`

type CreateTaskCommentParams struct {
	TaskID          uuid.UUID
	UserID          uuid.UUID
	Content         string
	ParentCommentID pgtype.UUID
}

func (q *Queries) CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskComment,
		arg.TaskID,
		arg.UserID,
		arg.Content,
		arg.ParentCommentID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTaskComments = `-- name: ListTaskComments :many
WITH recursive paginated_parent_comments AS (
  SELECT
    c.id,
    c.task_id,
    c.user_id,
    c.content,
    c.parent_comment_id,
    c.created_at,
    c.updated_at
  FROM task_comments c
  WHERE c.task_id = $1
    AND c.parent_comment_id IS NULL
    AND (c.created_at, c.id) < ($3::timestamptz, $4::uuid)
  ORDER BY c.created_at DESC, c.id DESC
  LIMIT $2
),
comment_tree AS (
  SELECT
    p.id,
    p.task_id,
    p.user_id,
    p.content,
    p.parent_comment_id,
    p.created_at,
    p.updated_at,
    0 as level,
    p.created_at as root_created_at,
    u.id as comment_user_id,
    u.name as comment_user_name,
    u.email as comment_user_email,
    u.created_at as comment_user_created_at,
    u.updated_at as comment_user_updated_at
  FROM paginated_parent_comments p
  JOIN users u ON p.user_id = u.id
  UNION ALL
  SELECT
    c.id,
    c.task_id,
    c.user_id,
    c.content,
    c.parent_comment_id,
    c.created_at,
    c.updated_at,
    ct.level + 1 as level,
    ct.root_created_at,
    u.id as comment_user_id,
    u.name as comment_user_name,
    u.email as comment_user_email,
    u.created_at as comment_user_created_at,
    u.updated_at as comment_user_updated_at
  FROM task_comments c
  JOIN users u ON c.user_id = u.id
  JOIN comment_tree ct ON c.parent_comment_id = ct.id
)
SELECT
  id, task_id, user_id, content, parent_comment_id, created_at, updated_at, level, root_created_at, comment_user_id, comment_user_name, comment_user_email, comment_user_created_at, comment_user_updated_at
FROM comment_tree
ORDER BY root_created_at DESC, created_at ASC, id ASC
`

type ListTaskCommentsParams struct {
	TaskID  uuid.UUID
	Limit   int32
	Column3 pgtype.Timestamptz
	Column4 uuid.UUID
}

type ListTaskCommentsRow struct {
	ID                   uuid.UUID
	TaskID               uuid.UUID
	UserID               uuid.UUID
	Content              string
	ParentCommentID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Level                int32
	RootCreatedAt        pgtype.Timestamptz
	CommentUserID        uuid.UUID
	CommentUserName      string
	CommentUserEmail     string
	CommentUserCreatedAt pgtype.Timestamptz
	CommentUserUpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments,
		arg.TaskID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCommentsRow
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.ParentCommentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Level,
			&i.RootCreatedAt,
			&i.CommentUserID,
			&i.CommentUserName,
			&i.CommentUserEmail,
			&i.CommentUserCreatedAt,
			&i.CommentUserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
