// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tasks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByProjectIdAndStatus = `-- name: CountTasksByProjectIdAndStatus :many
SELECT t.status, COUNT(*) AS count
FROM tasks t
WHERE t.project_id = $1
  AND ($2::text[] IS NULL OR t.status = ANY($2::text[]))
GROUP BY t.status
`

type CountTasksByProjectIdAndStatusParams struct {
	ProjectID uuid.UUID
	Column2   []string
}

type CountTasksByProjectIdAndStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountTasksByProjectIdAndStatus(ctx context.Context, arg CountTasksByProjectIdAndStatusParams) ([]CountTasksByProjectIdAndStatusRow, error) {
	rows, err := q.db.Query(ctx, countTasksByProjectIdAndStatus, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByProjectIdAndStatusRow
	for rows.Next() {
		var i CountTasksByProjectIdAndStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, author_id, responsible_id, priority, due_date, task_order) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning id
`

type CreateTaskParams struct {
	ProjectID     uuid.UUID
	Title         string
	Description   string
	Status        string
	AuthorID      uuid.UUID
	ResponsibleID pgtype.UUID
	Priority      string
	DueDate       pgtype.Timestamptz
	TaskOrder     int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AuthorID,
		arg.ResponsibleID,
		arg.Priority,
		arg.DueDate,
		arg.TaskOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTaskChange = `-- name: CreateTaskChange :one
INSERT INTO task_changes (update_id, field, old_value, new_value, subject_id) VALUES ($1, $2, $3, $4, $5) returning id
`

type CreateTaskChangeParams struct {
	UpdateID  pgtype.UUID
	Field     string
	OldValue  string
	NewValue  string
	SubjectID pgtype.UUID
}

func (q *Queries) CreateTaskChange(ctx context.Context, arg CreateTaskChangeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskChange,
		arg.UpdateID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.SubjectID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTaskTag = `-- name: CreateTaskTag :exec
INSERT INTO task_tags (task_id, name) VALUES ($1, $2)
`

type CreateTaskTagParams struct {
	TaskID uuid.UUID
	Name   string
}

func (q *Queries) CreateTaskTag(ctx context.Context, arg CreateTaskTagParams) error {
	_, err := q.db.Exec(ctx, createTaskTag, arg.TaskID, arg.Name)
	return err
}

const createTaskUpdate = `-- name: CreateTaskUpdate :one
INSERT INTO task_updates (task_id, user_id, update_type) VALUES ($1, $2, $3) returning id
`

type CreateTaskUpdateParams struct {
	TaskID     uuid.UUID
	UserID     uuid.UUID
	UpdateType string
}

func (q *Queries) CreateTaskUpdate(ctx context.Context, arg CreateTaskUpdateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskUpdate, arg.TaskID, arg.UserID, arg.UpdateType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllTaskTags = `-- name: DeleteAllTaskTags :exec
DELETE FROM task_tags WHERE task_id = $1
`

func (q *Queries) DeleteAllTaskTags(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllTaskTags, taskID)
	return err
}

const deleteTaskTag = `-- name: DeleteTaskTag :exec
DELETE FROM task_tags WHERE task_id = $1 AND name = $2
`

type DeleteTaskTagParams struct {
	TaskID uuid.UUID
	Name   string
}

func (q *Queries) DeleteTaskTag(ctx context.Context, arg DeleteTaskTagParams) error {
	_, err := q.db.Exec(ctx, deleteTaskTag, arg.TaskID, arg.Name)
	return err
}

const getProjectTaskAfterId = `-- name: GetProjectTaskAfterId :one
SELECT t.id, t.project_id, t.title, t.description, t.status, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order 
FROM tasks t
WHERE t.task_order >= (SELECT task_order FROM tasks t2 WHERE t2.id = $1)
  AND t.project_id = $2
  AND t.id != $1
ORDER BY t.task_order ASC, t.updated_at DESC
LIMIT 1
`

type GetProjectTaskAfterIdParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectTaskAfterId(ctx context.Context, arg GetProjectTaskAfterIdParams) (Task, error) {
	row := q.db.QueryRow(ctx, getProjectTaskAfterId, arg.ID, arg.ProjectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Priority,
		&i.DueDate,
		&i.DoneAt,
		&i.ResponsibleID,
		&i.TaskOrder,
	)
	return i, err
}

const getSmallestOrderProjectTask = `-- name: GetSmallestOrderProjectTask :one
SELECT id, project_id, title, description, status, created_at, updated_at, author_id, priority, due_date, done_at, responsible_id, task_order FROM tasks WHERE project_id = $1 ORDER BY task_order ASC, updated_at DESC LIMIT 1
`

func (q *Queries) GetSmallestOrderProjectTask(ctx context.Context, projectID uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getSmallestOrderProjectTask, projectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Priority,
		&i.DueDate,
		&i.DoneAt,
		&i.ResponsibleID,
		&i.TaskOrder,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
WITH task_tags_cte AS (
  SELECT
    tt.name as task_tag_name
  from task_tags tt
  WHERE tt.task_id = $1
), task_changes_cte AS (
  SELECT
    tc.id as task_change_id,
    tc.update_id as task_change_update_id,
    tc.subject_id as task_change_subject_id,
    tc.field as task_change_field,
    tc.old_value as task_change_old_value,
    tc.new_value as task_change_new_value,
    tc.created_at as task_change_created_at,
    s.name as task_change_subject_name,
    s.email as task_change_subject_email,
    s.created_at as task_change_subject_created_at
   FROM task_changes tc
   LEFT JOIN users s ON s.id = tc.subject_id
   ORDER BY tc.created_at DESC
), task_updates_cte AS (
  SELECT
    tu.id as task_update_id,
    tu.task_id as task_update_task_id,
    tu.user_id as task_update_user_id,
    tu.update_type as task_update_update_type,
    tu.created_at as task_update_created_at,
    u.name as task_update_user_name,
    u.email as task_update_user_email,
    u.created_at as task_update_user_created_at,
    coalesce(jsonb_agg(
      jsonb_build_object(
        'id', tc.task_change_id,
        'update_id', tc.task_change_update_id,
        'subject_id', tc.task_change_subject_id,
        'field', tc.task_change_field,
        'old_value', tc.task_change_old_value,
        'new_value', tc.task_change_new_value,
        'created_at', tc.task_change_created_at,
        'subject', jsonb_build_object(
          'id', tc.task_change_subject_id,
          'name', tc.task_change_subject_name,
          'email', tc.task_change_subject_email,
          'created_at', tc.task_change_subject_created_at
        )
      )
    ) filter (where tc.task_change_id is not null), '[]'::jsonb) as task_changes
   FROM task_updates tu
   LEFT JOIN users u ON u.id = tu.user_id
   LEFT JOIN task_changes_cte tc ON tc.task_change_update_id = tu.id
   WHERE tu.task_id = $1 
   GROUP BY tu.id, u.name, u.email, u.created_at
   ORDER BY tu.created_at DESC
)
SELECT
  t.id as task_id,
  t.project_id as task_project_id,
  t.title as task_title,
  t.description as task_description,
  t.status as task_status,
  t.priority as task_priority,
  t.responsible_id as task_responsible_id,
  t.due_date as task_due_date,
  t.done_at as task_done_at,
  t.task_order as task_order,
  t.created_at as task_created_at,
  t.updated_at as task_updated_at,
  t.author_id as task_author_id,
  a.name as task_author_name,
  a.email as task_author_email,
  a.created_at as task_author_created_at,
  r.name as task_responsible_name,
  r.email as task_responsible_email,
  r.created_at as task_responsible_created_at,
  (select coalesce(jsonb_agg(tt.task_tag_name) filter (where tt.task_tag_name is not null), '[]') from task_tags_cte tt) as tags,
  (select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', tu.task_update_id,
      'task_id', tu.task_update_task_id,
      'user_id', tu.task_update_user_id,
      'update_type', tu.task_update_update_type,
      'created_at', tu.task_update_created_at,
      'user', jsonb_build_object(
        'id', tu.task_update_user_id,
        'name', tu.task_update_user_name,
        'email', tu.task_update_user_email,
        'created_at', tu.task_update_user_created_at
      ),
      'changes', tu.task_changes
    )
  ) filter (where tu.task_update_id is not null), '[]'::jsonb) from task_updates_cte tu) as updates
FROM tasks t
LEFT JOIN users a ON a.id = t.author_id
LEFT JOIN users r ON r.id = t.responsible_id
WHERE t.id = $1
`

type GetTaskByIdRow struct {
	TaskID                   uuid.UUID
	TaskProjectID            uuid.UUID
	TaskTitle                string
	TaskDescription          string
	TaskStatus               string
	TaskPriority             string
	TaskResponsibleID        pgtype.UUID
	TaskDueDate              pgtype.Timestamptz
	TaskDoneAt               pgtype.Timestamptz
	TaskOrder                int32
	TaskCreatedAt            pgtype.Timestamptz
	TaskUpdatedAt            pgtype.Timestamptz
	TaskAuthorID             uuid.UUID
	TaskAuthorName           pgtype.Text
	TaskAuthorEmail          pgtype.Text
	TaskAuthorCreatedAt      pgtype.Timestamptz
	TaskResponsibleName      pgtype.Text
	TaskResponsibleEmail     pgtype.Text
	TaskResponsibleCreatedAt pgtype.Timestamptz
	Tags                     interface{}
	Updates                  interface{}
}

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (GetTaskByIdRow, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i GetTaskByIdRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskProjectID,
		&i.TaskTitle,
		&i.TaskDescription,
		&i.TaskStatus,
		&i.TaskPriority,
		&i.TaskResponsibleID,
		&i.TaskDueDate,
		&i.TaskDoneAt,
		&i.TaskOrder,
		&i.TaskCreatedAt,
		&i.TaskUpdatedAt,
		&i.TaskAuthorID,
		&i.TaskAuthorName,
		&i.TaskAuthorEmail,
		&i.TaskAuthorCreatedAt,
		&i.TaskResponsibleName,
		&i.TaskResponsibleEmail,
		&i.TaskResponsibleCreatedAt,
		&i.Tags,
		&i.Updates,
	)
	return i, err
}

const listTasksByProjectId = `-- name: ListTasksByProjectId :many
SELECT
  t.id, t.project_id, t.title, t.description, t.status, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order,
  a.id as author_author_id,
  a.name as author_name,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
LEFT JOIN users a ON a.id = t.author_id
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE project_id = $1
AND (
  cardinality($3::text[]) = 0
  OR t.status = ANY($3::text[])
)
AND (
  $4::timestamptz IS NULL
  OR t.task_order > $5::integer
  OR (t.task_order = $5::integer AND t.updated_at < $4::timestamptz)
)
GROUP BY t.id, a.name, a.id, r.name, r.id
ORDER BY t.task_order ASC, t.updated_at DESC
LIMIT $2
`

type ListTasksByProjectIdParams struct {
	ProjectID       uuid.UUID
	Limit           int32
	Statuses        []string
	CursorUpdatedAt pgtype.Timestamptz
	TaskOrder       pgtype.Int4
}

type ListTasksByProjectIdRow struct {
	ID                       uuid.UUID
	ProjectID                uuid.UUID
	Title                    string
	Description              string
	Status                   string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	AuthorID                 uuid.UUID
	Priority                 string
	DueDate                  pgtype.Timestamptz
	DoneAt                   pgtype.Timestamptz
	ResponsibleID            pgtype.UUID
	TaskOrder                int32
	AuthorAuthorID           pgtype.UUID
	AuthorName               pgtype.Text
	ResponsibleResponsibleID pgtype.UUID
	ResponsibleName          pgtype.Text
	Tags                     interface{}
}

func (q *Queries) ListTasksByProjectId(ctx context.Context, arg ListTasksByProjectIdParams) ([]ListTasksByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectId,
		arg.ProjectID,
		arg.Limit,
		arg.Statuses,
		arg.CursorUpdatedAt,
		arg.TaskOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectIdRow
	for rows.Next() {
		var i ListTasksByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.AuthorAuthorID,
			&i.AuthorName,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDueTasks = `-- name: ListUserDueTasks :many
SELECT
  t.id, t.project_id, t.title, t.description, t.status, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order,
  p.id as project_project_id,
  p.name as project_name,
  p.description as project_description,
  p.created_at as project_created_at,
  p.updated_at as project_updated_at,
  p.user_id as project_user_id,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
JOIN projects p ON p.id = t.project_id
WHERE t.responsible_id = $1
AND (
  cardinality($3::text[]) = 0
  OR t.status = ANY($3::text[])
)
AND (
  $4::timestamptz IS NULL
  OR $5::timestamptz IS NULL
  OR t.due_date > $4::timestamptz
  OR (t.due_date = $4::timestamptz AND t.updated_at < $5::timestamptz)
)
GROUP BY t.id, r.name, r.id, p.id, p.name, p.description, p.created_at, p.updated_at, p.user_id
ORDER BY t.due_date ASC, t.updated_at DESC
LIMIT $2
`

type ListUserDueTasksParams struct {
	ResponsibleID   pgtype.UUID
	Limit           int32
	Statuses        []string
	CursorDueDate   pgtype.Timestamptz
	CursorUpdatedAt pgtype.Timestamptz
}

type ListUserDueTasksRow struct {
	ID                       uuid.UUID
	ProjectID                uuid.UUID
	Title                    string
	Description              string
	Status                   string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	AuthorID                 uuid.UUID
	Priority                 string
	DueDate                  pgtype.Timestamptz
	DoneAt                   pgtype.Timestamptz
	ResponsibleID            pgtype.UUID
	TaskOrder                int32
	ProjectProjectID         uuid.UUID
	ProjectName              string
	ProjectDescription       string
	ProjectCreatedAt         pgtype.Timestamptz
	ProjectUpdatedAt         pgtype.Timestamptz
	ProjectUserID            uuid.UUID
	ResponsibleResponsibleID pgtype.UUID
	ResponsibleName          pgtype.Text
	Tags                     interface{}
}

func (q *Queries) ListUserDueTasks(ctx context.Context, arg ListUserDueTasksParams) ([]ListUserDueTasksRow, error) {
	rows, err := q.db.Query(ctx, listUserDueTasks,
		arg.ResponsibleID,
		arg.Limit,
		arg.Statuses,
		arg.CursorDueDate,
		arg.CursorUpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDueTasksRow
	for rows.Next() {
		var i ListUserDueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.ProjectProjectID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
			&i.ProjectUserID,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks t
SET task_order = $1,
    status = $2,
    updated_at = CURRENT_TIMESTAMP
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $3
WHERE t.id = $4
  AND p.id = t.project_id
RETURNING t.id, t.task_order, t.status
`

type MoveTaskParams struct {
	TaskOrder int32
	Status    string
	UserID    uuid.UUID
	ID        uuid.UUID
}

type MoveTaskRow struct {
	ID        uuid.UUID
	TaskOrder int32
	Status    string
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (MoveTaskRow, error) {
	row := q.db.QueryRow(ctx, moveTask,
		arg.TaskOrder,
		arg.Status,
		arg.UserID,
		arg.ID,
	)
	var i MoveTaskRow
	err := row.Scan(&i.ID, &i.TaskOrder, &i.Status)
	return i, err
}

const searchTasksForUser = `-- name: SearchTasksForUser :many
WITH project_ids_cte AS (
  SELECT DISTINCT pm.project_id
  FROM project_members pm
  WHERE pm.user_id = $1
)
SELECT t.id, t.project_id, t.title, t.description, t.status, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order,
  p.id as project_project_id,
  p.name as project_name,
  p.description as project_description,
  p.created_at as project_created_at,
  p.updated_at as project_updated_at,
  p.user_id as project_user_id,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  r.email as responsible_email,
  r.created_at as responsible_created_at,
  a.id as author_author_id,
  a.name as author_name,
  a.email as author_email,
  a.created_at as author_created_at,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN users a ON a.id = t.author_id
JOIN projects p ON p.id = t.project_id
JOIN project_ids_cte pi ON pi.project_id = t.project_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE ($3::text IS NULL OR (t.title ILIKE '%' || $3::text || '%' OR t.description ILIKE '%' || $3::text || '%'))
AND (
  $4::timestamptz IS NULL
  OR $5::timestamptz IS NULL
  OR t.due_date > $4::timestamptz
  OR (t.due_date = $4::timestamptz AND t.updated_at < $5::timestamptz)
) AND (
  cardinality($6::text[]) = 0
  OR t.status = ANY($6::text[])
)
GROUP BY t.id, p.id, p.name, p.description, p.created_at, p.updated_at, p.user_id, r.id, r.name, r.email, r.created_at, a.id, a.name, a.email, a.created_at
ORDER BY t.due_date ASC, t.updated_at DESC
LIMIT $2
`

type SearchTasksForUserParams struct {
	UserID          uuid.UUID
	Limit           int32
	Query           pgtype.Text
	CursorDueDate   pgtype.Timestamptz
	CursorUpdatedAt pgtype.Timestamptz
	Statuses        []string
}

type SearchTasksForUserRow struct {
	ID                       uuid.UUID
	ProjectID                uuid.UUID
	Title                    string
	Description              string
	Status                   string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	AuthorID                 uuid.UUID
	Priority                 string
	DueDate                  pgtype.Timestamptz
	DoneAt                   pgtype.Timestamptz
	ResponsibleID            pgtype.UUID
	TaskOrder                int32
	ProjectProjectID         uuid.UUID
	ProjectName              string
	ProjectDescription       string
	ProjectCreatedAt         pgtype.Timestamptz
	ProjectUpdatedAt         pgtype.Timestamptz
	ProjectUserID            uuid.UUID
	ResponsibleResponsibleID pgtype.UUID
	ResponsibleName          pgtype.Text
	ResponsibleEmail         pgtype.Text
	ResponsibleCreatedAt     pgtype.Timestamptz
	AuthorAuthorID           pgtype.UUID
	AuthorName               pgtype.Text
	AuthorEmail              pgtype.Text
	AuthorCreatedAt          pgtype.Timestamptz
	Tags                     interface{}
}

func (q *Queries) SearchTasksForUser(ctx context.Context, arg SearchTasksForUserParams) ([]SearchTasksForUserRow, error) {
	rows, err := q.db.Query(ctx, searchTasksForUser,
		arg.UserID,
		arg.Limit,
		arg.Query,
		arg.CursorDueDate,
		arg.CursorUpdatedAt,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTasksForUserRow
	for rows.Next() {
		var i SearchTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.ProjectProjectID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
			&i.ProjectUserID,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.ResponsibleEmail,
			&i.ResponsibleCreatedAt,
			&i.AuthorAuthorID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorCreatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET title = $1, description = $2, status = $3, task_order = $4, priority = $5, due_date = $6, responsible_id = $7, done_at = $8, updated_at = CURRENT_TIMESTAMP WHERE id = $9
`

type UpdateTaskParams struct {
	Title         string
	Description   string
	Status        string
	TaskOrder     int32
	Priority      string
	DueDate       pgtype.Timestamptz
	ResponsibleID pgtype.UUID
	DoneAt        pgtype.Timestamptz
	ID            uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.TaskOrder,
		arg.Priority,
		arg.DueDate,
		arg.ResponsibleID,
		arg.DoneAt,
		arg.ID,
	)
	return err
}

const updateTaskOrder = `-- name: UpdateTaskOrder :exec
UPDATE tasks SET task_order = $1 WHERE id = $2
`

type UpdateTaskOrderParams struct {
	TaskOrder int32
	ID        uuid.UUID
}

func (q *Queries) UpdateTaskOrder(ctx context.Context, arg UpdateTaskOrderParams) error {
	_, err := q.db.Exec(ctx, updateTaskOrder, arg.TaskOrder, arg.ID)
	return err
}
