// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tasks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByProjectIdAndColumn = `-- name: CountTasksByProjectIdAndColumn :many
SELECT t.project_column_id, COUNT(*) AS count
FROM tasks t
WHERE t.project_id = $1
  AND t.archived_at IS NULL
  AND ($2::uuid[] IS NULL OR t.project_column_id = ANY($2::uuid[]))
GROUP BY t.project_column_id
`

type CountTasksByProjectIdAndColumnParams struct {
	ProjectID uuid.UUID
	Column2   []uuid.UUID
}

type CountTasksByProjectIdAndColumnRow struct {
	ProjectColumnID uuid.UUID
	Count           int64
}

func (q *Queries) CountTasksByProjectIdAndColumn(ctx context.Context, arg CountTasksByProjectIdAndColumnParams) ([]CountTasksByProjectIdAndColumnRow, error) {
	rows, err := q.db.Query(ctx, countTasksByProjectIdAndColumn, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByProjectIdAndColumnRow
	for rows.Next() {
		var i CountTasksByProjectIdAndColumnRow
		if err := rows.Scan(&i.ProjectColumnID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, project_column_id, author_id, responsible_id, priority, due_date, done_at, task_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning id
`

type CreateTaskParams struct {
	ProjectID       uuid.UUID
	Title           string
	Description     string
	ProjectColumnID uuid.UUID
	AuthorID        uuid.UUID
	ResponsibleID   pgtype.UUID
	Priority        string
	DueDate         pgtype.Timestamptz
	DoneAt          pgtype.Timestamptz
	TaskOrder       string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.ProjectColumnID,
		arg.AuthorID,
		arg.ResponsibleID,
		arg.Priority,
		arg.DueDate,
		arg.DoneAt,
		arg.TaskOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTaskChange = `-- name: CreateTaskChange :one
INSERT INTO task_changes (update_id, field, old_value, new_value, subject_id, old_value_id, new_value_id, old_display_value, new_display_value) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning id
`

type CreateTaskChangeParams struct {
	UpdateID        pgtype.UUID
	Field           string
	OldValue        string
	NewValue        string
	SubjectID       pgtype.UUID
	OldValueID      pgtype.UUID
	NewValueID      pgtype.UUID
	OldDisplayValue pgtype.Text
	NewDisplayValue pgtype.Text
}

func (q *Queries) CreateTaskChange(ctx context.Context, arg CreateTaskChangeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskChange,
		arg.UpdateID,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
		arg.SubjectID,
		arg.OldValueID,
		arg.NewValueID,
		arg.OldDisplayValue,
		arg.NewDisplayValue,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTaskTag = `-- name: CreateTaskTag :exec
INSERT INTO task_tags (task_id, name) VALUES ($1, $2)
`

type CreateTaskTagParams struct {
	TaskID uuid.UUID
	Name   string
}

func (q *Queries) CreateTaskTag(ctx context.Context, arg CreateTaskTagParams) error {
	_, err := q.db.Exec(ctx, createTaskTag, arg.TaskID, arg.Name)
	return err
}

const createTaskUpdate = `-- name: CreateTaskUpdate :one
INSERT INTO task_updates (task_id, user_id, update_type) VALUES ($1, $2, $3) returning id
`

type CreateTaskUpdateParams struct {
	TaskID     uuid.UUID
	UserID     uuid.UUID
	UpdateType string
}

func (q *Queries) CreateTaskUpdate(ctx context.Context, arg CreateTaskUpdateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskUpdate, arg.TaskID, arg.UserID, arg.UpdateType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllTaskTags = `-- name: DeleteAllTaskTags :exec
DELETE FROM task_tags WHERE task_id = $1
`

func (q *Queries) DeleteAllTaskTags(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllTaskTags, taskID)
	return err
}

const deleteTaskTag = `-- name: DeleteTaskTag :exec
DELETE FROM task_tags WHERE task_id = $1 AND name = $2
`

type DeleteTaskTagParams struct {
	TaskID uuid.UUID
	Name   string
}

func (q *Queries) DeleteTaskTag(ctx context.Context, arg DeleteTaskTagParams) error {
	_, err := q.db.Exec(ctx, deleteTaskTag, arg.TaskID, arg.Name)
	return err
}

const getFirstTaskInColumn = `-- name: GetFirstTaskInColumn :one
SELECT id, project_id, title, description, project_column_id, created_at, updated_at, author_id, priority, due_date, done_at, archived_at, responsible_id, task_order
FROM tasks
WHERE project_id = $1
  AND project_column_id = $2
  AND archived_at IS NULL
ORDER BY task_order ASC, updated_at DESC
LIMIT 1
`

type GetFirstTaskInColumnParams struct {
	ProjectID       uuid.UUID
	ProjectColumnID uuid.UUID
}

type GetFirstTaskInColumnRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Title           string
	Description     string
	ProjectColumnID uuid.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AuthorID        uuid.UUID
	Priority        string
	DueDate         pgtype.Timestamptz
	DoneAt          pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	ResponsibleID   pgtype.UUID
	TaskOrder       string
}

func (q *Queries) GetFirstTaskInColumn(ctx context.Context, arg GetFirstTaskInColumnParams) (GetFirstTaskInColumnRow, error) {
	row := q.db.QueryRow(ctx, getFirstTaskInColumn, arg.ProjectID, arg.ProjectColumnID)
	var i GetFirstTaskInColumnRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.ProjectColumnID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Priority,
		&i.DueDate,
		&i.DoneAt,
		&i.ArchivedAt,
		&i.ResponsibleID,
		&i.TaskOrder,
	)
	return i, err
}

const getProjectTaskAfterId = `-- name: GetProjectTaskAfterId :one
SELECT t.id, t.project_id, t.title, t.description, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order, t.project_column_id, t.archived_at 
FROM tasks t
WHERE t.task_order >= (SELECT task_order FROM tasks t2 WHERE t2.id = $1)
  AND t.project_id = $2
  AND t.project_column_id = (SELECT project_column_id FROM tasks t2 WHERE t2.id = $1)
  AND t.id != $1
  AND t.archived_at IS NULL
ORDER BY t.task_order ASC, t.updated_at DESC
LIMIT 1
`

type GetProjectTaskAfterIdParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectTaskAfterId(ctx context.Context, arg GetProjectTaskAfterIdParams) (Task, error) {
	row := q.db.QueryRow(ctx, getProjectTaskAfterId, arg.ID, arg.ProjectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Priority,
		&i.DueDate,
		&i.DoneAt,
		&i.ResponsibleID,
		&i.TaskOrder,
		&i.ProjectColumnID,
		&i.ArchivedAt,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
WITH task_tags_cte AS (
  SELECT
    tt.name as task_tag_name
  from task_tags tt
  WHERE tt.task_id = $1
), task_changes_cte AS (
  SELECT
    tc.id as task_change_id,
    tc.update_id as task_change_update_id,
    tc.subject_id as task_change_subject_id,
    tc.old_value_id as task_change_old_value_id,
    tc.new_value_id as task_change_new_value_id,
    tc.field as task_change_field,
    tc.old_value as task_change_old_value,
    tc.new_value as task_change_new_value,
    tc.old_display_value as task_change_old_display_value,
    tc.new_display_value as task_change_new_display_value,
    tc.created_at as task_change_created_at,
    s.name as task_change_subject_name,
    s.email as task_change_subject_email,
    s.created_at as task_change_subject_created_at,
    old_r.name as task_change_old_value_name,
    new_r.name as task_change_new_value_name
   FROM task_changes tc
   LEFT JOIN users s ON s.id = tc.subject_id
   LEFT JOIN users old_r ON tc.field = 'responsible_id' AND old_r.id::text = nullif(tc.old_value, '') AND tc.old_display_value IS NULL
   LEFT JOIN users new_r ON tc.field = 'responsible_id' AND new_r.id::text = nullif(tc.new_value, '') AND tc.new_display_value IS NULL
), task_updates_cte AS (
  SELECT
    tu.id as task_update_id,
    tu.task_id as task_update_task_id,
    tu.user_id as task_update_user_id,
    tu.update_type as task_update_update_type,
    tu.created_at as task_update_created_at,
    u.name as task_update_user_name,
    u.email as task_update_user_email,
    u.created_at as task_update_user_created_at,
    coalesce(jsonb_agg(
      jsonb_build_object(
        'id', tc.task_change_id,
        'update_id', tc.task_change_update_id,
        'subject_id', tc.task_change_subject_id,
        'old_value_id', tc.task_change_old_value_id,
        'new_value_id', tc.task_change_new_value_id,
        'field', tc.task_change_field,
        'old_value', tc.task_change_old_value,
        'new_value', tc.task_change_new_value,
        'old_display_value', CASE
          WHEN tc.task_change_old_display_value IS NOT NULL THEN tc.task_change_old_display_value
          WHEN tc.task_change_field = 'responsible_id' THEN tc.task_change_old_value_name
          ELSE NULL
        END,
        'new_display_value', CASE
          WHEN tc.task_change_new_display_value IS NOT NULL THEN tc.task_change_new_display_value
          WHEN tc.task_change_field = 'responsible_id' THEN tc.task_change_new_value_name
          ELSE NULL
        END,
        'created_at', tc.task_change_created_at,
        'subject', jsonb_build_object(
          'id', tc.task_change_subject_id,
          'name', tc.task_change_subject_name,
          'email', tc.task_change_subject_email,
          'created_at', tc.task_change_subject_created_at
        )
      )
      ORDER BY tc.task_change_created_at DESC, tc.task_change_id DESC
    ) filter (where tc.task_change_id is not null), '[]'::jsonb) as task_changes
   FROM task_updates tu
   LEFT JOIN users u ON u.id = tu.user_id
   LEFT JOIN task_changes_cte tc ON tc.task_change_update_id = tu.id
   WHERE tu.task_id = $1 
   GROUP BY tu.id, u.name, u.email, u.created_at
   ORDER BY tu.created_at DESC
)
SELECT
  t.id as task_id,
  t.project_id as task_project_id,
  t.title as task_title,
  t.description as task_description,
  t.project_column_id as task_project_column_id,
  t.priority as task_priority,
  t.responsible_id as task_responsible_id,
  t.due_date as task_due_date,
  t.done_at as task_done_at,
  t.archived_at as task_archived_at,
  t.task_order as task_order,
  t.created_at as task_created_at,
  t.updated_at as task_updated_at,
  t.author_id as task_author_id,
  a.name as task_author_name,
  a.email as task_author_email,
  a.created_at as task_author_created_at,
  r.name as task_responsible_name,
  r.email as task_responsible_email,
  r.created_at as task_responsible_created_at,
  jsonb_build_object(
    'id', ps.id,
    'project_id', ps.project_id,
    'name', ps.name,
    'color', ps.color,
    'position', ps.position,
    'is_done_column', ps.is_done_column,
    'created_at', ps.created_at,
    'updated_at', ps.updated_at
  ) as project_column,
  (select coalesce(jsonb_agg(tt.task_tag_name) filter (where tt.task_tag_name is not null), '[]') from task_tags_cte tt) as tags,
  (select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', tu.task_update_id,
      'task_id', tu.task_update_task_id,
      'user_id', tu.task_update_user_id,
      'update_type', tu.task_update_update_type,
      'created_at', tu.task_update_created_at,
      'user', jsonb_build_object(
        'id', tu.task_update_user_id,
        'name', tu.task_update_user_name,
        'email', tu.task_update_user_email,
        'created_at', tu.task_update_user_created_at
      ),
      'changes', tu.task_changes
    )
    ORDER BY tu.task_update_created_at DESC, tu.task_update_id DESC
  ) filter (where tu.task_update_id is not null), '[]'::jsonb) from task_updates_cte tu) as updates
FROM tasks t
LEFT JOIN users a ON a.id = t.author_id
LEFT JOIN users r ON r.id = t.responsible_id
JOIN project_columns ps ON ps.id = t.project_column_id
WHERE t.id = $1
`

type GetTaskByIdRow struct {
	TaskID                   uuid.UUID
	TaskProjectID            uuid.UUID
	TaskTitle                string
	TaskDescription          string
	TaskProjectColumnID      uuid.UUID
	TaskPriority             string
	TaskResponsibleID        pgtype.UUID
	TaskDueDate              pgtype.Timestamptz
	TaskDoneAt               pgtype.Timestamptz
	TaskArchivedAt           pgtype.Timestamptz
	TaskOrder                string
	TaskCreatedAt            pgtype.Timestamptz
	TaskUpdatedAt            pgtype.Timestamptz
	TaskAuthorID             uuid.UUID
	TaskAuthorName           pgtype.Text
	TaskAuthorEmail          pgtype.Text
	TaskAuthorCreatedAt      pgtype.Timestamptz
	TaskResponsibleName      pgtype.Text
	TaskResponsibleEmail     pgtype.Text
	TaskResponsibleCreatedAt pgtype.Timestamptz
	ProjectColumn            []byte
	Tags                     interface{}
	Updates                  interface{}
}

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (GetTaskByIdRow, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i GetTaskByIdRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskProjectID,
		&i.TaskTitle,
		&i.TaskDescription,
		&i.TaskProjectColumnID,
		&i.TaskPriority,
		&i.TaskResponsibleID,
		&i.TaskDueDate,
		&i.TaskDoneAt,
		&i.TaskArchivedAt,
		&i.TaskOrder,
		&i.TaskCreatedAt,
		&i.TaskUpdatedAt,
		&i.TaskAuthorID,
		&i.TaskAuthorName,
		&i.TaskAuthorEmail,
		&i.TaskAuthorCreatedAt,
		&i.TaskResponsibleName,
		&i.TaskResponsibleEmail,
		&i.TaskResponsibleCreatedAt,
		&i.ProjectColumn,
		&i.Tags,
		&i.Updates,
	)
	return i, err
}

const listTasksByProjectId = `-- name: ListTasksByProjectId :many
SELECT
  t.id, t.project_id, t.title, t.description, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order, t.project_column_id, t.archived_at,
  ps.id as project_column_id_2,
  ps.project_id as project_column_project_id,
  ps.name as project_column_name,
  ps.color as project_column_color,
  ps.position as project_column_position,
  ps.is_done_column as project_column_is_done_column,
  ps.created_at as project_column_created_at,
  ps.updated_at as project_column_updated_at,
  a.id as author_author_id,
  a.name as author_name,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
JOIN project_columns ps ON ps.id = t.project_column_id
LEFT JOIN users a ON a.id = t.author_id
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE t.project_id = $1
AND (
  cardinality($3::uuid[]) = 0
  OR t.project_column_id = ANY($3::uuid[])
)
AND (
  $4::boolean = true
  OR t.archived_at IS NULL
)
AND (
  $5::timestamptz IS NULL
  OR t.task_order > $6::text
  OR (t.task_order = $6::text AND t.updated_at < $5::timestamptz)
)
GROUP BY t.id, ps.id, a.name, a.id, r.name, r.id
ORDER BY t.task_order ASC, t.updated_at DESC
LIMIT $2
`

type ListTasksByProjectIdParams struct {
	ProjectID        uuid.UUID
	Limit            int32
	ProjectColumnIds []uuid.UUID
	Archived         bool
	CursorUpdatedAt  pgtype.Timestamptz
	TaskOrder        pgtype.Text
}

type ListTasksByProjectIdRow struct {
	ID                        uuid.UUID
	ProjectID                 uuid.UUID
	Title                     string
	Description               string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	AuthorID                  uuid.UUID
	Priority                  string
	DueDate                   pgtype.Timestamptz
	DoneAt                    pgtype.Timestamptz
	ResponsibleID             pgtype.UUID
	TaskOrder                 string
	ProjectColumnID           uuid.UUID
	ArchivedAt                pgtype.Timestamptz
	ProjectColumnID2          uuid.UUID
	ProjectColumnProjectID    uuid.UUID
	ProjectColumnName         string
	ProjectColumnColor        string
	ProjectColumnPosition     int32
	ProjectColumnIsDoneColumn bool
	ProjectColumnCreatedAt    pgtype.Timestamptz
	ProjectColumnUpdatedAt    pgtype.Timestamptz
	AuthorAuthorID            pgtype.UUID
	AuthorName                pgtype.Text
	ResponsibleResponsibleID  pgtype.UUID
	ResponsibleName           pgtype.Text
	Tags                      interface{}
}

func (q *Queries) ListTasksByProjectId(ctx context.Context, arg ListTasksByProjectIdParams) ([]ListTasksByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectId,
		arg.ProjectID,
		arg.Limit,
		arg.ProjectColumnIds,
		arg.Archived,
		arg.CursorUpdatedAt,
		arg.TaskOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectIdRow
	for rows.Next() {
		var i ListTasksByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.ProjectColumnID,
			&i.ArchivedAt,
			&i.ProjectColumnID2,
			&i.ProjectColumnProjectID,
			&i.ProjectColumnName,
			&i.ProjectColumnColor,
			&i.ProjectColumnPosition,
			&i.ProjectColumnIsDoneColumn,
			&i.ProjectColumnCreatedAt,
			&i.ProjectColumnUpdatedAt,
			&i.AuthorAuthorID,
			&i.AuthorName,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDueTasks = `-- name: ListUserDueTasks :many
SELECT
  t.id, t.project_id, t.title, t.description, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order, t.project_column_id, t.archived_at,
  ps.id as project_column_id_2,
  ps.project_id as project_column_project_id,
  ps.name as project_column_name,
  ps.color as project_column_color,
  ps.position as project_column_position,
  ps.is_done_column as project_column_is_done_column,
  ps.created_at as project_column_created_at,
  ps.updated_at as project_column_updated_at,
  p.id as project_project_id,
  p.name as project_name,
  p.description as project_description,
  p.created_at as project_created_at,
  p.updated_at as project_updated_at,
  p.user_id as project_user_id,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
JOIN project_columns ps ON ps.id = t.project_column_id
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
JOIN projects p ON p.id = t.project_id
WHERE t.responsible_id = $1
AND t.due_date IS NOT NULL
AND t.archived_at IS NULL
AND ps.is_done_column = false
AND (
  $3::timestamptz IS NULL
  OR $4::timestamptz IS NULL
  OR t.due_date > $3::timestamptz
  OR (t.due_date = $3::timestamptz AND t.updated_at < $4::timestamptz)
)
GROUP BY t.id, ps.id, r.name, r.id, p.id, p.name, p.description, p.created_at, p.updated_at, p.user_id
ORDER BY t.due_date ASC, t.updated_at DESC
LIMIT $2
`

type ListUserDueTasksParams struct {
	ResponsibleID   pgtype.UUID
	Limit           int32
	CursorDueDate   pgtype.Timestamptz
	CursorUpdatedAt pgtype.Timestamptz
}

type ListUserDueTasksRow struct {
	ID                        uuid.UUID
	ProjectID                 uuid.UUID
	Title                     string
	Description               string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	AuthorID                  uuid.UUID
	Priority                  string
	DueDate                   pgtype.Timestamptz
	DoneAt                    pgtype.Timestamptz
	ResponsibleID             pgtype.UUID
	TaskOrder                 string
	ProjectColumnID           uuid.UUID
	ArchivedAt                pgtype.Timestamptz
	ProjectColumnID2          uuid.UUID
	ProjectColumnProjectID    uuid.UUID
	ProjectColumnName         string
	ProjectColumnColor        string
	ProjectColumnPosition     int32
	ProjectColumnIsDoneColumn bool
	ProjectColumnCreatedAt    pgtype.Timestamptz
	ProjectColumnUpdatedAt    pgtype.Timestamptz
	ProjectProjectID          uuid.UUID
	ProjectName               string
	ProjectDescription        string
	ProjectCreatedAt          pgtype.Timestamptz
	ProjectUpdatedAt          pgtype.Timestamptz
	ProjectUserID             uuid.UUID
	ResponsibleResponsibleID  pgtype.UUID
	ResponsibleName           pgtype.Text
	Tags                      interface{}
}

func (q *Queries) ListUserDueTasks(ctx context.Context, arg ListUserDueTasksParams) ([]ListUserDueTasksRow, error) {
	rows, err := q.db.Query(ctx, listUserDueTasks,
		arg.ResponsibleID,
		arg.Limit,
		arg.CursorDueDate,
		arg.CursorUpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDueTasksRow
	for rows.Next() {
		var i ListUserDueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.ProjectColumnID,
			&i.ArchivedAt,
			&i.ProjectColumnID2,
			&i.ProjectColumnProjectID,
			&i.ProjectColumnName,
			&i.ProjectColumnColor,
			&i.ProjectColumnPosition,
			&i.ProjectColumnIsDoneColumn,
			&i.ProjectColumnCreatedAt,
			&i.ProjectColumnUpdatedAt,
			&i.ProjectProjectID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
			&i.ProjectUserID,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks t
SET task_order = $1,
    project_column_id = $2,
    done_at = $3,
    updated_at = CURRENT_TIMESTAMP
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = $4
WHERE t.id = $5
  AND p.id = t.project_id
RETURNING t.id, t.task_order, t.project_column_id
`

type MoveTaskParams struct {
	TaskOrder       string
	ProjectColumnID uuid.UUID
	DoneAt          pgtype.Timestamptz
	UserID          uuid.UUID
	ID              uuid.UUID
}

type MoveTaskRow struct {
	ID              uuid.UUID
	TaskOrder       string
	ProjectColumnID uuid.UUID
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (MoveTaskRow, error) {
	row := q.db.QueryRow(ctx, moveTask,
		arg.TaskOrder,
		arg.ProjectColumnID,
		arg.DoneAt,
		arg.UserID,
		arg.ID,
	)
	var i MoveTaskRow
	err := row.Scan(&i.ID, &i.TaskOrder, &i.ProjectColumnID)
	return i, err
}

const searchTasksForUser = `-- name: SearchTasksForUser :many
WITH project_ids_cte AS (
  SELECT DISTINCT pm.project_id
  FROM project_members pm
  WHERE pm.user_id = $1
)
SELECT t.id, t.project_id, t.title, t.description, t.created_at, t.updated_at, t.author_id, t.priority, t.due_date, t.done_at, t.responsible_id, t.task_order, t.project_column_id, t.archived_at,
  ps.id as project_column_id_2,
  ps.project_id as project_column_project_id,
  ps.name as project_column_name,
  ps.color as project_column_color,
  ps.position as project_column_position,
  ps.is_done_column as project_column_is_done_column,
  ps.created_at as project_column_created_at,
  ps.updated_at as project_column_updated_at,
  p.id as project_project_id,
  p.name as project_name,
  p.description as project_description,
  p.created_at as project_created_at,
  p.updated_at as project_updated_at,
  p.user_id as project_user_id,
  r.id as responsible_responsible_id,
  r.name as responsible_name,
  r.email as responsible_email,
  r.created_at as responsible_created_at,
  a.id as author_author_id,
  a.name as author_name,
  a.email as author_email,
  a.created_at as author_created_at,
  coalesce(jsonb_agg(tt.name) filter (where tt.name is not null), '[]') as tags
FROM tasks t
JOIN project_columns ps ON ps.id = t.project_column_id
LEFT JOIN users r ON r.id = t.responsible_id
LEFT JOIN users a ON a.id = t.author_id
JOIN projects p ON p.id = t.project_id
JOIN project_ids_cte pi ON pi.project_id = t.project_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
WHERE ($3::text IS NULL OR (t.title ILIKE '%' || $3::text || '%' OR t.description ILIKE '%' || $3::text || '%'))
AND t.archived_at IS NULL
AND ps.is_done_column = false
AND (
  $4::timestamptz IS NULL
  OR $5::timestamptz IS NULL
  OR t.due_date > $4::timestamptz
  OR (t.due_date = $4::timestamptz AND t.updated_at < $5::timestamptz)
)
GROUP BY t.id, ps.id, p.id, p.name, p.description, p.created_at, p.updated_at, p.user_id, r.id, r.name, r.email, r.created_at, a.id, a.name, a.email, a.created_at
ORDER BY t.due_date ASC, t.updated_at DESC
LIMIT $2
`

type SearchTasksForUserParams struct {
	UserID          uuid.UUID
	Limit           int32
	Query           pgtype.Text
	CursorDueDate   pgtype.Timestamptz
	CursorUpdatedAt pgtype.Timestamptz
}

type SearchTasksForUserRow struct {
	ID                        uuid.UUID
	ProjectID                 uuid.UUID
	Title                     string
	Description               string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	AuthorID                  uuid.UUID
	Priority                  string
	DueDate                   pgtype.Timestamptz
	DoneAt                    pgtype.Timestamptz
	ResponsibleID             pgtype.UUID
	TaskOrder                 string
	ProjectColumnID           uuid.UUID
	ArchivedAt                pgtype.Timestamptz
	ProjectColumnID2          uuid.UUID
	ProjectColumnProjectID    uuid.UUID
	ProjectColumnName         string
	ProjectColumnColor        string
	ProjectColumnPosition     int32
	ProjectColumnIsDoneColumn bool
	ProjectColumnCreatedAt    pgtype.Timestamptz
	ProjectColumnUpdatedAt    pgtype.Timestamptz
	ProjectProjectID          uuid.UUID
	ProjectName               string
	ProjectDescription        string
	ProjectCreatedAt          pgtype.Timestamptz
	ProjectUpdatedAt          pgtype.Timestamptz
	ProjectUserID             uuid.UUID
	ResponsibleResponsibleID  pgtype.UUID
	ResponsibleName           pgtype.Text
	ResponsibleEmail          pgtype.Text
	ResponsibleCreatedAt      pgtype.Timestamptz
	AuthorAuthorID            pgtype.UUID
	AuthorName                pgtype.Text
	AuthorEmail               pgtype.Text
	AuthorCreatedAt           pgtype.Timestamptz
	Tags                      interface{}
}

func (q *Queries) SearchTasksForUser(ctx context.Context, arg SearchTasksForUserParams) ([]SearchTasksForUserRow, error) {
	rows, err := q.db.Query(ctx, searchTasksForUser,
		arg.UserID,
		arg.Limit,
		arg.Query,
		arg.CursorDueDate,
		arg.CursorUpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTasksForUserRow
	for rows.Next() {
		var i SearchTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Priority,
			&i.DueDate,
			&i.DoneAt,
			&i.ResponsibleID,
			&i.TaskOrder,
			&i.ProjectColumnID,
			&i.ArchivedAt,
			&i.ProjectColumnID2,
			&i.ProjectColumnProjectID,
			&i.ProjectColumnName,
			&i.ProjectColumnColor,
			&i.ProjectColumnPosition,
			&i.ProjectColumnIsDoneColumn,
			&i.ProjectColumnCreatedAt,
			&i.ProjectColumnUpdatedAt,
			&i.ProjectProjectID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.ProjectCreatedAt,
			&i.ProjectUpdatedAt,
			&i.ProjectUserID,
			&i.ResponsibleResponsibleID,
			&i.ResponsibleName,
			&i.ResponsibleEmail,
			&i.ResponsibleCreatedAt,
			&i.AuthorAuthorID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorCreatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET title = $1, description = $2, project_column_id = $3, task_order = $4, priority = $5, due_date = $6, responsible_id = $7, done_at = $8, archived_at = $9, updated_at = CURRENT_TIMESTAMP WHERE id = $10
`

type UpdateTaskParams struct {
	Title           string
	Description     string
	ProjectColumnID uuid.UUID
	TaskOrder       string
	Priority        string
	DueDate         pgtype.Timestamptz
	ResponsibleID   pgtype.UUID
	DoneAt          pgtype.Timestamptz
	ArchivedAt      pgtype.Timestamptz
	ID              uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.ProjectColumnID,
		arg.TaskOrder,
		arg.Priority,
		arg.DueDate,
		arg.ResponsibleID,
		arg.DoneAt,
		arg.ArchivedAt,
		arg.ID,
	)
	return err
}
