// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: projectchat/apikey/v1/apikey.proto

package apikeyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BearerSecret  string                 `protobuf:"bytes,1,opt,name=bearer_secret,json=bearerSecret,proto3" json:"bearer_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_projectchat_apikey_v1_apikey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_apikey_v1_apikey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_apikey_v1_apikey_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetBearerSecret() string {
	if x != nil {
		return x.BearerSecret
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_projectchat_apikey_v1_apikey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_apikey_v1_apikey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_apikey_v1_apikey_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_projectchat_apikey_v1_apikey_proto protoreflect.FileDescriptor

const file_projectchat_apikey_v1_apikey_proto_rawDesc = "" +
	"\n" +
	"\"projectchat/apikey/v1/apikey.proto\x12\x15projectchat.apikey.v1\":\n" +
	"\x13AuthenticateRequest\x12#\n" +
	"\rbearer_secret\x18\x01 \x01(\tR\fbearerSecret\"^\n" +
	"\x14AuthenticateResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes2x\n" +
	"\rAPIKeyService\x12g\n" +
	"\fAuthenticate\x12*.projectchat.apikey.v1.AuthenticateRequest\x1a+.projectchat.apikey.v1.AuthenticateResponseBDZBgithub.com/gabrielnakaema/project-chat/internal/apikey/v1;apikeyv1b\x06proto3"

var (
	file_projectchat_apikey_v1_apikey_proto_rawDescOnce sync.Once
	file_projectchat_apikey_v1_apikey_proto_rawDescData []byte
)

func file_projectchat_apikey_v1_apikey_proto_rawDescGZIP() []byte {
	file_projectchat_apikey_v1_apikey_proto_rawDescOnce.Do(func() {
		file_projectchat_apikey_v1_apikey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectchat_apikey_v1_apikey_proto_rawDesc), len(file_projectchat_apikey_v1_apikey_proto_rawDesc)))
	})
	return file_projectchat_apikey_v1_apikey_proto_rawDescData
}

var file_projectchat_apikey_v1_apikey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_projectchat_apikey_v1_apikey_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: projectchat.apikey.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: projectchat.apikey.v1.AuthenticateResponse
}
var file_projectchat_apikey_v1_apikey_proto_depIdxs = []int32{
	0, // 0: projectchat.apikey.v1.APIKeyService.Authenticate:input_type -> projectchat.apikey.v1.AuthenticateRequest
	1, // 1: projectchat.apikey.v1.APIKeyService.Authenticate:output_type -> projectchat.apikey.v1.AuthenticateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_projectchat_apikey_v1_apikey_proto_init() }
func file_projectchat_apikey_v1_apikey_proto_init() {
	if File_projectchat_apikey_v1_apikey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectchat_apikey_v1_apikey_proto_rawDesc), len(file_projectchat_apikey_v1_apikey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectchat_apikey_v1_apikey_proto_goTypes,
		DependencyIndexes: file_projectchat_apikey_v1_apikey_proto_depIdxs,
		MessageInfos:      file_projectchat_apikey_v1_apikey_proto_msgTypes,
	}.Build()
	File_projectchat_apikey_v1_apikey_proto = out.File
	file_projectchat_apikey_v1_apikey_proto_goTypes = nil
	file_projectchat_apikey_v1_apikey_proto_depIdxs = nil
}
