// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: projectchat/project/v1/project.proto

package projectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{1}
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MemberRole    string                 `protobuf:"bytes,2,opt,name=member_role,json=memberRole,proto3" json:"member_role,omitempty"`
	FilterByRole  bool                   `protobuf:"varint,3,opt,name=filter_by_role,json=filterByRole,proto3" json:"filter_by_role,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListProjectsRequest) GetMemberRole() string {
	if x != nil {
		return x.MemberRole
	}
	return ""
}

func (x *ListProjectsRequest) GetFilterByRole() bool {
	if x != nil {
		return x.FilterByRole
	}
	return false
}

func (x *ListProjectsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectJson   []byte                 `protobuf:"bytes,1,opt,name=project_json,json=projectJson,proto3" json:"project_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectResponse) GetProjectJson() []byte {
	if x != nil {
		return x.ProjectJson
	}
	return nil
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectsJson  []byte                 `protobuf:"bytes,1,opt,name=projects_json,json=projectsJson,proto3" json:"projects_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsResponse) GetProjectsJson() []byte {
	if x != nil {
		return x.ProjectsJson
	}
	return nil
}

var File_projectchat_project_v1_project_proto protoreflect.FileDescriptor

const file_projectchat_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"$projectchat/project/v1/project.proto\x12\x16projectchat.project.v1\"L\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x15\n" +
	"\x13CheckAccessResponse\"K\n" +
	"\x11GetProjectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x98\x01\n" +
	"\x13ListProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vmember_role\x18\x02 \x01(\tR\n" +
	"memberRole\x12$\n" +
	"\x0efilter_by_role\x18\x03 \x01(\bR\ffilterByRole\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\"7\n" +
	"\x12GetProjectResponse\x12!\n" +
	"\fproject_json\x18\x01 \x01(\fR\vprojectJson\";\n" +
	"\x14ListProjectsResponse\x12#\n" +
	"\rprojects_json\x18\x01 \x01(\fR\fprojectsJson2\xc8\x02\n" +
	"\x0eProjectService\x12f\n" +
	"\vCheckAccess\x12*.projectchat.project.v1.CheckAccessRequest\x1a+.projectchat.project.v1.CheckAccessResponse\x12c\n" +
	"\n" +
	"GetProject\x12).projectchat.project.v1.GetProjectRequest\x1a*.projectchat.project.v1.GetProjectResponse\x12i\n" +
	"\fListProjects\x12+.projectchat.project.v1.ListProjectsRequest\x1a,.projectchat.project.v1.ListProjectsResponseBFZDgithub.com/gabrielnakaema/project-chat/internal/project/v1;projectv1b\x06proto3"

var (
	file_projectchat_project_v1_project_proto_rawDescOnce sync.Once
	file_projectchat_project_v1_project_proto_rawDescData []byte
)

func file_projectchat_project_v1_project_proto_rawDescGZIP() []byte {
	file_projectchat_project_v1_project_proto_rawDescOnce.Do(func() {
		file_projectchat_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectchat_project_v1_project_proto_rawDesc), len(file_projectchat_project_v1_project_proto_rawDesc)))
	})
	return file_projectchat_project_v1_project_proto_rawDescData
}

var file_projectchat_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_projectchat_project_v1_project_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),   // 0: projectchat.project.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),  // 1: projectchat.project.v1.CheckAccessResponse
	(*GetProjectRequest)(nil),    // 2: projectchat.project.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),  // 3: projectchat.project.v1.ListProjectsRequest
	(*GetProjectResponse)(nil),   // 4: projectchat.project.v1.GetProjectResponse
	(*ListProjectsResponse)(nil), // 5: projectchat.project.v1.ListProjectsResponse
}
var file_projectchat_project_v1_project_proto_depIdxs = []int32{
	0, // 0: projectchat.project.v1.ProjectService.CheckAccess:input_type -> projectchat.project.v1.CheckAccessRequest
	2, // 1: projectchat.project.v1.ProjectService.GetProject:input_type -> projectchat.project.v1.GetProjectRequest
	3, // 2: projectchat.project.v1.ProjectService.ListProjects:input_type -> projectchat.project.v1.ListProjectsRequest
	1, // 3: projectchat.project.v1.ProjectService.CheckAccess:output_type -> projectchat.project.v1.CheckAccessResponse
	4, // 4: projectchat.project.v1.ProjectService.GetProject:output_type -> projectchat.project.v1.GetProjectResponse
	5, // 5: projectchat.project.v1.ProjectService.ListProjects:output_type -> projectchat.project.v1.ListProjectsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_projectchat_project_v1_project_proto_init() }
func file_projectchat_project_v1_project_proto_init() {
	if File_projectchat_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectchat_project_v1_project_proto_rawDesc), len(file_projectchat_project_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectchat_project_v1_project_proto_goTypes,
		DependencyIndexes: file_projectchat_project_v1_project_proto_depIdxs,
		MessageInfos:      file_projectchat_project_v1_project_proto_msgTypes,
	}.Build()
	File_projectchat_project_v1_project_proto = out.File
	file_projectchat_project_v1_project_proto_goTypes = nil
	file_projectchat_project_v1_project_proto_depIdxs = nil
}
