// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: projectchat/project/v1/project.proto

package projectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_projectchat_project_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projectchat_project_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_projectchat_project_v1_project_proto_rawDescGZIP(), []int{1}
}

var File_projectchat_project_v1_project_proto protoreflect.FileDescriptor

const file_projectchat_project_v1_project_proto_rawDesc = "" +
	"\n" +
	"$projectchat/project/v1/project.proto\x12\x16projectchat.project.v1\"L\n" +
	"\x12CheckAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x15\n" +
	"\x13CheckAccessResponse2x\n" +
	"\x0eProjectService\x12f\n" +
	"\vCheckAccess\x12*.projectchat.project.v1.CheckAccessRequest\x1a+.projectchat.project.v1.CheckAccessResponseBFZDgithub.com/gabrielnakaema/project-chat/internal/project/v1;projectv1b\x06proto3"

var (
	file_projectchat_project_v1_project_proto_rawDescOnce sync.Once
	file_projectchat_project_v1_project_proto_rawDescData []byte
)

func file_projectchat_project_v1_project_proto_rawDescGZIP() []byte {
	file_projectchat_project_v1_project_proto_rawDescOnce.Do(func() {
		file_projectchat_project_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projectchat_project_v1_project_proto_rawDesc), len(file_projectchat_project_v1_project_proto_rawDesc)))
	})
	return file_projectchat_project_v1_project_proto_rawDescData
}

var file_projectchat_project_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_projectchat_project_v1_project_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),  // 0: projectchat.project.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil), // 1: projectchat.project.v1.CheckAccessResponse
}
var file_projectchat_project_v1_project_proto_depIdxs = []int32{
	0, // 0: projectchat.project.v1.ProjectService.CheckAccess:input_type -> projectchat.project.v1.CheckAccessRequest
	1, // 1: projectchat.project.v1.ProjectService.CheckAccess:output_type -> projectchat.project.v1.CheckAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_projectchat_project_v1_project_proto_init() }
func file_projectchat_project_v1_project_proto_init() {
	if File_projectchat_project_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projectchat_project_v1_project_proto_rawDesc), len(file_projectchat_project_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projectchat_project_v1_project_proto_goTypes,
		DependencyIndexes: file_projectchat_project_v1_project_proto_depIdxs,
		MessageInfos:      file_projectchat_project_v1_project_proto_msgTypes,
	}.Build()
	File_projectchat_project_v1_project_proto = out.File
	file_projectchat_project_v1_project_proto_goTypes = nil
	file_projectchat_project_v1_project_proto_depIdxs = nil
}
