/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedMcpAccessRouteImport } from './routes/_protected/mcp-access'
import { Route as ProtectedSearchRouteRouteImport } from './routes/_protected/search/route'
import { Route as ProtectedProjectsRouteRouteImport } from './routes/_protected/projects/route'
import { Route as ProtectedSearchIndexRouteImport } from './routes/_protected/search/index'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected/projects/index'
import { Route as ProtectedProjectsProjectIdIndexRouteImport } from './routes/_protected/projects/$projectId/index'
import { Route as ProtectedProjectsProjectIdChatRouteImport } from './routes/_protected/projects/$projectId/chat'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMcpAccessRoute = ProtectedMcpAccessRouteImport.update({
  id: '/mcp-access',
  path: '/mcp-access',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchRouteRoute = ProtectedSearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProjectsRouteRoute = ProtectedProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchIndexRoute = ProtectedSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSearchRouteRoute,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProjectsRouteRoute,
} as any)
const ProtectedProjectsProjectIdIndexRoute =
  ProtectedProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => ProtectedProjectsRouteRoute,
  } as any)
const ProtectedProjectsProjectIdChatRoute =
  ProtectedProjectsProjectIdChatRouteImport.update({
    id: '/$projectId/chat',
    path: '/$projectId/chat',
    getParentRoute: () => ProtectedProjectsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/projects': typeof ProtectedProjectsRouteRouteWithChildren
  '/search': typeof ProtectedSearchRouteRouteWithChildren
  '/mcp-access': typeof ProtectedMcpAccessRoute
  '/projects/': typeof ProtectedProjectsIndexRoute
  '/search/': typeof ProtectedSearchIndexRoute
  '/projects/$projectId/chat': typeof ProtectedProjectsProjectIdChatRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/mcp-access': typeof ProtectedMcpAccessRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/search': typeof ProtectedSearchIndexRoute
  '/projects/$projectId/chat': typeof ProtectedProjectsProjectIdChatRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/projects': typeof ProtectedProjectsRouteRouteWithChildren
  '/_protected/search': typeof ProtectedSearchRouteRouteWithChildren
  '/_protected/mcp-access': typeof ProtectedMcpAccessRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/search/': typeof ProtectedSearchIndexRoute
  '/_protected/projects/$projectId/chat': typeof ProtectedProjectsProjectIdChatRoute
  '/_protected/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/projects'
    | '/search'
    | '/mcp-access'
    | '/projects/'
    | '/search/'
    | '/projects/$projectId/chat'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/mcp-access'
    | '/projects'
    | '/search'
    | '/projects/$projectId/chat'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/sign-up'
    | '/_protected/projects'
    | '/_protected/search'
    | '/_protected/mcp-access'
    | '/_protected/projects/'
    | '/_protected/search/'
    | '/_protected/projects/$projectId/chat'
    | '/_protected/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/mcp-access': {
      id: '/_protected/mcp-access'
      path: '/mcp-access'
      fullPath: '/mcp-access'
      preLoaderRoute: typeof ProtectedMcpAccessRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/projects': {
      id: '/_protected/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search/': {
      id: '/_protected/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof ProtectedSearchIndexRouteImport
      parentRoute: typeof ProtectedSearchRouteRoute
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedProjectsRouteRoute
    }
    '/_protected/projects/$projectId/': {
      id: '/_protected/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProtectedProjectsRouteRoute
    }
    '/_protected/projects/$projectId/chat': {
      id: '/_protected/projects/$projectId/chat'
      path: '/$projectId/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProtectedProjectsProjectIdChatRouteImport
      parentRoute: typeof ProtectedProjectsRouteRoute
    }
  }
}

interface ProtectedProjectsRouteRouteChildren {
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
  ProtectedProjectsProjectIdChatRoute: typeof ProtectedProjectsProjectIdChatRoute
  ProtectedProjectsProjectIdIndexRoute: typeof ProtectedProjectsProjectIdIndexRoute
}

const ProtectedProjectsRouteRouteChildren: ProtectedProjectsRouteRouteChildren =
  {
    ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
    ProtectedProjectsProjectIdChatRoute: ProtectedProjectsProjectIdChatRoute,
    ProtectedProjectsProjectIdIndexRoute: ProtectedProjectsProjectIdIndexRoute,
  }

const ProtectedProjectsRouteRouteWithChildren =
  ProtectedProjectsRouteRoute._addFileChildren(
    ProtectedProjectsRouteRouteChildren,
  )

interface ProtectedSearchRouteRouteChildren {
  ProtectedSearchIndexRoute: typeof ProtectedSearchIndexRoute
}

const ProtectedSearchRouteRouteChildren: ProtectedSearchRouteRouteChildren = {
  ProtectedSearchIndexRoute: ProtectedSearchIndexRoute,
}

const ProtectedSearchRouteRouteWithChildren =
  ProtectedSearchRouteRoute._addFileChildren(ProtectedSearchRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedProjectsRouteRoute: typeof ProtectedProjectsRouteRouteWithChildren
  ProtectedSearchRouteRoute: typeof ProtectedSearchRouteRouteWithChildren
  ProtectedMcpAccessRoute: typeof ProtectedMcpAccessRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedProjectsRouteRoute: ProtectedProjectsRouteRouteWithChildren,
  ProtectedSearchRouteRoute: ProtectedSearchRouteRouteWithChildren,
  ProtectedMcpAccessRoute: ProtectedMcpAccessRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
