// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: outbox.sql

package outboxqueries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fetchUnpublishedOutboxMessages = `-- name: FetchUnpublishedOutboxMessages :many
SELECT id, topic, aggregate_id, payload
FROM outbox_messages
WHERE published_at IS NULL
ORDER BY created_at, id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type FetchUnpublishedOutboxMessagesRow struct {
	ID          uuid.UUID
	Topic       string
	AggregateID pgtype.UUID
	Payload     []byte
}

func (q *Queries) FetchUnpublishedOutboxMessages(ctx context.Context, limit int32) ([]FetchUnpublishedOutboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, fetchUnpublishedOutboxMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchUnpublishedOutboxMessagesRow
	for rows.Next() {
		var i FetchUnpublishedOutboxMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.AggregateID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (topic, aggregate_id, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxMessageParams struct {
	Topic       string
	AggregateID pgtype.UUID
	Payload     []byte
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage, arg.Topic, arg.AggregateID, arg.Payload)
	return err
}

const markOutboxMessagesPublished = `-- name: MarkOutboxMessagesPublished :exec
UPDATE outbox_messages
SET published_at = current_timestamp
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkOutboxMessagesPublished(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxMessagesPublished, dollar_1)
	return err
}
