name: frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_API_URL: ${{ secrets.API_URL }}

      - name: Upload build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "frontend/dist/*"
          target: "${{ secrets.FRONTEND_DIR }}/releases/${{ github.run_id }}/"
          strip_components: 2

      - name: Update symlink
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.FRONTEND_DIR }}
            ln -sfn releases/${{ github.run_id }} current
